### ISSUE TITLE
Undefined variables

### ISSUE THREAD

**Issue by markushausammann** [easyphp/easyphp-devserver#1]
Notice: Undefined variable: date in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\modules\xdebugmanager\easyphp+.php on line 29

Notice: Undefined variable: date in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\modules\xdebugmanager\easyphp+.php on line 40

**Comment by easyphp** [comment]
A new version of Xdebug Manager is in development. Which configuration do you use ? You can join the discussion : https://github.com/easyphp/DEVSERVER/discussions and tell us what you need. @groovenectar @markushausammann @chapterjason @ve3
