### ISSUE TITLE
PHP / windows10 : extension not loaded at startup when changing default installation directory

### ISSUE THREAD

**Issue by papattes** [easyphp/easyphp-devserver#100]
Hello !

I had a problem, on windows 10, loading PHP extensions at startup because the php.ini, rewritten by the startup script, contained the wrong directory for "extension_dir".

My installation of EaysyPHP was done in a different directory than the one proposed by default: 

> "F:\server\easyPHP\Devserver\16.1\"

The **eds-app-actions.php** script rewrote in php.ini :

`extension_dir = "F:\server\easyPHP\Devserver\.1\ext"`

and the extensions were not loaded.

To remedy the problem, I modified in **"...\eds-binaries\php\phpXXXXvcXXXXXXXX\eds-app-actions.php"**

`$Replacement = '${1}' . __DIR__ . '\ext' . '$3';`

by

`$Replacement = '${1}' . addslashes(__DIR__) . '\\ext' . '$3';`

Hopefully this will help ;)

**Comment by easyphp** [comment]
Thanks. Added to the next version.
