### ISSUE TITLE
Nginx won't download

### ISSUE THREAD

**Issue by constashare** [easyphp/easyphp-devserver#101]
I tried to update my devserver with nginx since it didn't come with it but I get connection error when I hit the download button.

**Comment by easyphp** [comment]
We checked. No problem there. You can download Nginx.

**Comment by constashare** [comment]
![easy-php](https://cloud.githubusercontent.com/assets/18107884/24643450/120cf806-18dc-11e7-9f9e-b559a79dcf02.PNG)

I get server unreachable.

**Comment by easyphp** [comment]
It works on our side. Can you try a other browser or computer ? The file is there and the server is running fine.
