### ISSUE TITLE
SQL error: #1524 - Plugin '*2470C0C06DEE42FD1618BB99005ADCA2EC9D1E19' is not loaded

### ISSUE THREAD

**Issue by Mlocik97** [easyphp/easyphp-devserver#103]
I tried:
mysql -u root
mysqladmin -u root password NEWPASSWORD
mysql -u root -p

after I can join to phpMyAdmin but I haven't privileges (user = root).

[http://s30.postimg.org/g0w0ysx4x/screenshot_52.png](http://s30.postimg.org/g0w0ysx4x/screenshot_52.png)

**Comment by easyphp** [comment]
Could you be more specific ? If you're not talking about a bug, please ask your question on http://stackoverflow.com/ or there http://www.easyphp.org/discussions_devserver.php
