### ISSUE TITLE
EasyPHP startup error ordinal number 314

### ISSUE THREAD

**Issue by jiri-neruda** [easyphp/easyphp-devserver#107]
Hello, I'm getting from new version, EasyPHP 17, error with ordinal number 314 not located in php_openssl.dll. EasyPHP start, running, but never start the Apache server and BD server seems not to work either (or run, but in Dashboard isn't visible). I have tried 16.1.1 version, but no luck. Error went away, but servers don't start/change their status... Searched web for clues and found: Apache has problems with ssleay32.dll and libeay32.dll. Thought about replacing them...

Have you some tips or guesses how to make EasyPHP work (great) again?

P.S.: I'm using EasyPHP for long time, I don't want to go. :)

**Comment by easyphp** [comment]
Hi
Try a few things first:
- open the task manager (<kdb>Ctrl</kdb> + <kdb>Alt</kdb> + <kdb>Del</kdb>) and see if any server is running
- open `services` (Windows logo key + "services") and see if any server is installed as a service
- check your Windows [path](http://www.computerhope.com/issues/ch000549.htm) and see if a path includes PHP

**Comment by jiri-neruda** [comment]
Sorry for late answer to you advice, have some things to be made in work, this is for my local in home :)

I think you areright and found it:
1. in services no server is installed, I'll live with it. So every start => start EasyPHP => start servers.
2. Patch in Enviroment is wrong, I'll repair it.

Many thanks :)

**Comment by jiri-neruda** [comment]
Maybe if it helps...
Apache Error Log:
[Sat Apr 29 10:41:47.646851 2017] [core:warn] [pid 6676:tid 592] AH00098: pid file C:/EasyPHP/eds-binaries/httpserver/apache2425vc11x86x170429103710/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
PHP Deprecated:  Comments starting with '#' are deprecated in C:\\EasyPHP\\eds-binaries\\php\\php5630vc11x86x170429103710\\php.ini on line 886 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\\EasyPHP\\eds-binaries\\php\\php5630vc11x86x170429103710\\ext\\php_pdo_pgsql.dll' - Uveden\xef\xbf\xbd modul nebyl nalezen.\r\n in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\\EasyPHP\\eds-binaries\\php\\php5630vc11x86x170429103710\\ext\\php_pgsql.dll' - Uveden\xef\xbf\xbd modul nebyl nalezen.\r\n in Unknown on line 0
[Sat Apr 29 10:41:47.663367 2017] [mpm_winnt:notice] [pid 6676:tid 592] AH00455: Apache/2.4.25 (Win32) PHP/5.6.30 configured -- resuming normal operations
[Sat Apr 29 10:41:47.663367 2017] [mpm_winnt:notice] [pid 6676:tid 592] AH00456: Apache Lounge VC11 Server built: Dec 20 2016 13:02:04
[Sat Apr 29 10:41:47.663367 2017] [core:notice] [pid 6676:tid 592] AH00094: Command line: 'C:\\EasyPHP\\eds-binaries\\httpserver\\apache2425vc11x86x170429103710\\bin\\eds-httpserver.exe -d C:/EasyPHP/eds-binaries/httpserver/apache2425vc11x86x170429103710'
[Sat Apr 29 10:41:47.678359 2017] [mpm_winnt:notice] [pid 6676:tid 592] AH00418: Parent: Created child process 9852
PHP Deprecated:  Comments starting with '#' are deprecated in C:\\EasyPHP\\eds-binaries\\php\\php5630vc11x86x170429103710\\php.ini on line 886 in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\\EasyPHP\\eds-binaries\\php\\php5630vc11x86x170429103710\\ext\\php_pdo_pgsql.dll' - Uveden\xef\xbf\xbd modul nebyl nalezen.\r\n in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'C:\\EasyPHP\\eds-binaries\\php\\php5630vc11x86x170429103710\\ext\\php_pgsql.dll' - Uveden\xef\xbf\xbd modul nebyl nalezen.\r\n in Unknown on line 0
[Sat Apr 29 10:41:48.298654 2017] [mpm_winnt:notice] [pid 9852:tid 656] AH00354: Child: Starting 64 worker threads.


And the MySQL:
2017-04-29T08:39:36.681670Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
2017-04-29T08:39:36.681670Z 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
2017-04-29T08:39:36.681670Z 0 [Warning] 'NO_AUTO_CREATE_USER' sql mode was not set.
2017-04-29T08:39:36.681670Z 0 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
2017-04-29T08:39:36.681670Z 0 [Note] C:\EasyPHP\eds-binaries\dbserver\mysql5717x86x170429103710\bin\eds-dbserver.exe (mysqld 5.7.17) starting as process 1588 ...


And also I noticed, the server will run, reinstalled EasyPHP, but when I stop them windows make noise like error or warning is coming in. So server now starts, EasyPHP without error too. But EasyPHP Dashboard hase troubles to know, if the servers is running. It can't see, they are running, but I can't work with them in Dashboard, because Dashboard thing they are stopped.

**Comment by jiri-neruda** [comment]
Ok, can be closed, mystically Windows Update repaired what has been wrong. So EasyPHP now works ok.
