### ISSUE TITLE
Windows 8 - I am admin but "start as service" still grey

### ISSUE THREAD

**Issue by winini** [easyphp/easyphp-devserver#11]
hello,

EasyPhp works well, but I want that it start as a "service" but the checkbox "start the servers as a Service" remains disabled (greyed). Note that I am admininistrateur mode in Windows 8.1 (no password is important?). Have you a solution ?

Thanks

**Comment by lalbi** [comment]
Hello

I have the same problem as winini, does anyone know how to resolve this problem?

**Comment by winini** [comment]
Hello lalbi
I had finally resolved, but I only remember that it was not complicated. I think what I have uninstalled the software, and (even as admin), I reinstalled with right click "execute as admin". After that, the checkbox has returned normal.

**Comment by lalbi** [comment]
Thank you very much, i will try reinstalling again like you said.
