### ISSUE TITLE
EasyPHP Devserver 17 fail to start Apache 2.4.25 with PHP 7.1.3 on Windows 10

### ISSUE THREAD

**Issue by urosevic** [easyphp/easyphp-devserver#110]
I already use EasyPHP Devserver 16.1.1 with PHP 7.0.14 and it work just fine. I stop Apache and MySQL services and exit Devserver 16.1.1 before I attempt to start v17. Skype does not use port 80.

Now I fresh install Devserver v17 and Apache service start with default PHP 5.6.30 (on port 80), but I'm getting bunch of errors when I select bundled PHP 7.1.3. Check out screencast at [https://youtu.be/9MaqMR9-cYg](https://youtu.be/9MaqMR9-cYg)

Here is list of errors I'm getting in Windows error popup:

```
The procedure entry point zend_wrong_parameter_type_error@@12 could not be located in the dynamic link library C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\php\php713vc14x86x170503191122\ext\php_gettext.dll
The procedure entry point zend_forbid_dynamic_call could not be located in the dynamic link library C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\php\php713vc14x86x170503191122\ext\php_mbstring.dll
The procedure entry point mysqlnd_connection_connect could not be located in the dynamic link library C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\php\php713vc14x86x170503191122\ext\php_mysqli.dll
The procedure entry point mysqlnd_connection_connect could not be located in the dynamic link library C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\php\php713vc14x86x170503191122\ext\php_pdo_mysql.dll
The procedure entry point zend_get_executed_scope could not be located in the dynamic link library C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\php\php713vc14x86x170503191122\ext\php_pgsql.dll
```

When I comment out all those extensions in php.ini and try to start Apache again, then start fail with following lines in apache error log file:

```
[Wed May 03 20:10:43.072859 2017] [core:warn] [pid 12336:tid 652] AH00098: pid file C:/Program Files (x86)/EasyPHP-Devserver-17/eds-binaries/httpserver/apache2425vc11x86x170503191122/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
PHP Warning:  PHP Startup: bz2: Unable to initialize module\nModule compiled with module API=20160303\nPHP    compiled with module API=20151012\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: gd: Unable to initialize module\nModule compiled with module API=20160303\nPHP    compiled with module API=20151012\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: exif: Unable to initialize module\nModule compiled with module API=20160303\nPHP    compiled with module API=20151012\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: sockets: Unable to initialize module\nModule compiled with module API=20160303\nPHP    compiled with module API=20151012\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: sqlite3: Unable to initialize module\nModule compiled with module API=20160303\nPHP    compiled with module API=20151012\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: xsl: Unable to initialize module\nModule compiled with module API=20160303\nPHP    compiled with module API=20151012\nThese options need to match\n in Unknown on line 0
```

When I comment out also these extensions in php.ini, then Apache also fail to start but with only following line in error log:

```
[Wed May 03 20:12:24.938074 2017] [core:warn] [pid 9880:tid 612] AH00098: pid file C:/Program Files (x86)/EasyPHP-Devserver-17/eds-binaries/httpserver/apache2425vc11x86x170503191122/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
```

When I copy PHP 7.0.14 module from v16.1.1 to v17, Apache on v17 run w/o error with that version of PHP.

So, how to deal with this and make Devserver 17 run Apache and PHP 7.1.3 w/o failing?

**Please note, MySQL service running w/o problem.**

**Comment by REJack** [comment]
This Issue looks like you have PHP 7.0 path added in your PATH and PHP 7.1 loads the Extensions from 7.0.

I had a simmilar issue but with other API.

**Comment by urosevic** [comment]
Thank you @REJack, that was exact issue here!

As soon as I change PHP in PATH variable (for System and for User) from PHP 7.0.14 on Devserver 16.1.1 to PHP 7.1.4 on Devserver v17, Apache now run with latest PHP (7.1.3 and 7.1.4).

@easyphp This tip should be added to [EasyPHP FAQ](http://www.easyphp.org/faq_devserver.php)

**Comment by REJack** [comment]
No problem.

I modded my Devserver to change a dir everytime the active PHP get changed 😄 after i got this issue.

**Comment by mikerockett** [comment]
@REJack - Would you mind sharing how you did that? I'd love to be able to do it myself as I maintain 4 different versions of PHP (5.4, 5.6, 7.0, 7.1). Having to stick to my built-up 7.0 devserver until this can be resolved.

**Comment by REJack** [comment]
Sure need this for my linting stuff inside my Editor 🛩, thsi work with all `httpserver` (apache & nginx)

__Important:__ After you added this tweak you need to run EasyPHP as Admin.

1. add these lines in your desired httpserver's `eds-app-actions.php` after line 45/46 
```php
// Update SymLink
$linkfile = '..\eds-binaries\php_link';
if(is_link($linkfile)) {
	rmdir($linkfile);
	$target = realpath('..\eds-binaries\php\\' . $php_folder);
	symlink($target, $linkfile);
}else{
	$target = realpath('..\eds-binaries\php\\' . $php_folder);
	symlink($target, $linkfile);
}
```
2. add `C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\php_link` in your(user) PATH or system's PATH (it work also with custom install paths)

regards REJack

**Comment by mikerockett** [comment]
Super, will try this out soon. Thanks. 👍

**Comment by mariusz-buk** [comment]
@REJack works perfectly!

**Comment by PrajaktaSoftware** [comment]
> 
> 
> Thank you @REJack, that was exact issue here!
> 
> As soon as I change PHP in PATH variable (for System and for User) from PHP 7.0.14 on Devserver 16.1.1 to PHP 7.1.4 on Devserver v17, Apache now run with latest PHP (7.1.3 and 7.1.4).
> 
> @easyphp This tip should be added to [EasyPHP FAQ](http://www.easyphp.org/faq_devserver.php)

Installed DevServer 17. But  unable to run 7.1.3 it when clicked on start nothing happens
How can I change the path, so that I can use php ver 7.1.3

**Comment by sessionstudio** [comment]
In my case, it was because Easyphp was trying to load a too large error.log file.
Deleting the server log file in eds-binaries\httpserver\apache2418x160331124251\logs
