### ISSUE TITLE
Trojan warning in Dev 17 Xdebug and Vhost modules

### ISSUE THREAD

**Issue by TomDeSmet** [easyphp/easyphp-devserver#111]
Title says it all. This way I can't install it at work.

**Comment by easyphp** [comment]
Strange. All apps are tested and we don't have any warning.
XdebugManager : https://www.virustotal.com/en/file/486273e68349fa1b10329e2749a4399cd8f96179cf897cc4fc48ed46d087009a/analysis/1494047462/
VirtualHostsManager : https://www.virustotal.com/en/file/63ef11d8c7cd9021455783fd09916c7b8fba58115f643abe0d25dc7f76051b9b/analysis/1494047471/

**Comment by TomDeSmet** [comment]
We use Symantec Endpoint and the threat we receive is for the Heur.advml.C Trojan.

**Comment by easyphp** [comment]
No worries. This is a false positive.

**Comment by jandw93** [comment]
Same here using Panda Antivirus.
