### ISSUE TITLE
array_set_zval_key cannot be found - easyphp startup

### ISSUE THREAD

**Issue by cnaudes** [easyphp/easyphp-devserver#114]
Hi all,

I am new here and pretty newbie as well with easy php.
I have been using easyphp for now a couple of months and I have never been faced to this issue.
I tried to change one setting in the php.ini and did a rollback afterwards and since then I've been facing the issue on startup: 
PHP Startup: sockets: Unable to initialize Module compiled withmodule API=20131226 PHP compiled module API=20100525. These options need to match.

Where can I find those options?? 
And after this message I always get the following:
The procedure entry point array_set_zval_key cannot be found (translation from french).

The option I uncommented was: ;extension=php_openssl.dll
I commented out again and it keeps on failing.
Any idea?
Thanks a lot.
Cyril.

**Comment by REJack** [comment]
@cnaudes Your PHP 5.6 loads modules from PHP 5.4 thats your problem, check your env path too from your user & system.

API=20131226 is PHP5.6
API=20100525 is PHP5.4

**Comment by cnaudes** [comment]
@REJack Indeed!!! Thanks a lot ! I've updated the path and it worked!!!
Thanks a lot again.
Cyril.
