### ISSUE TITLE
probleme avec easyphp 17.0

### ISSUE THREAD

**Issue by animefr** [easyphp/easyphp-devserver#115]

**Comment by animefr** [comment]
bonjour, je viens d'installer Easyphp 17.0 et je n'arrive pas a démarrer  les serveurs.

lorsque je démarre le dashboard, j'ai deux lignes en erreur.
![capture1](https://cloud.githubusercontent.com/assets/28789273/26217205/dcf2b022-3c06-11e7-9a88-b07fbe8e38e5.JPG)

j'ai beau cliquer sur "start" pour les démarrer, aucun des deux serveurs ne démarre.

que faire ? quelqu'un a-t-il déjà eu le problème ?

**Comment by mcnjr** [comment]
Hi @animefr,

J'ai eu un problème similaire, nous l'avons résolu ici:

https://github.com/easyphp/easyphp-devserver/issues/112

bonne chance!
