### ISSUE TITLE
intl and apcu

### ISSUE THREAD

**Issue by markushausammann** [easyphp/easyphp-devserver#12]
Please bundle intl and apcu, they're more frequently used than many of the bundled extensions.

**Comment by markushausammann** [comment]
I see that intl is already bundled. Please do the same with apcu.

**Comment by BenMorel** [comment]
+1.

For anyone reading this, in the meantime APCu can be downloaded from:
http://windows.php.net/downloads/pecl/releases/apcu/

Select the latest version, then the right combination for your installation (PHP `5.5`/`5.6`, `TS`/`NTS`, `VC9`/`VC11`, `x86`/`x64`). The right information can be found in your `phpinfo()`.

For my PHP 5.6.4 installation, the right file was `php_apcu-4.0.7-5.6-ts-vc11-x86.zip`. YMMV.

Copy the `apcu.dll` file to this directory:

    C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\binaries\php\php_runningversion\ext

The add this line to your `php.ini`:

    extension=php_apcu.dll

Restart Apache if easyPHP does not do it automatically.
