### ISSUE TITLE
Please indicate Xdebug version

### ISSUE THREAD

**Issue by Chealer** [easyphp/easyphp-devserver#120]
I am stuck with a problematic Xdebug because I use XAMPP, which ships Xdebug 2.2.5. I am considering to move to EasyPHP if that solves this problem, but while EasyPHP at least indicates it contains Xdebug, it does not indicate the version.

**Comment by hamza1886** [comment]
Run `php --version` on command prompt to see Xdebug version installed with EasyPHP.

**Comment by Chealer** [comment]
Thanks @hamza1886 , but the point of indicating the version is that potential users don't have to install EasyPHP just to see if it would fit their needs.

**Comment by hamza1886** [comment]
I am confused on "I am stuck with a problematic Xdebug". Please indicate your problem?

**Comment by Chealer** [comment]
That is a problem with XAMPP. The issue I reported is that if I would install EasyPHP, I would not necessarily solve my problem since I cannot tell what the Xdebug version shipped in EasyPHP is.

**Comment by hamza1886** [comment]
This is not a problem because you can always upgrade/downgrade your version of Xdebug shipped with EasyPHP. 

Default location of Xdebug `.dll` file in EasyPHP is `C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-binaries\php\php704vc14x86x160825011811\` on Windows (32-bit).

Download your required version of Xdebug from https://xdebug.org/download.php and replace it in above folder. Also, remember to update `zend_extension` value in `php.ini` file.

**Comment by Chealer** [comment]
I suppose this ticket should be moved to https://github.com/easyphp/easyphp-website

**Comment by hamza1886** [comment]
@Chealer Your Xdebug issue is not resolved yet?

**Comment by Chealer** [comment]
@hamza1886 I do not know. I do not even know if the issue is caused by an issue in Xdebug.

**Comment by Chealer** [comment]
Why was this ticket closed?

**Comment by Chealer** [comment]
@easyphp why did you close this ticket?

**Comment by easyphp** [comment]
A new version of Xdebug Manager is in development. Which configuration do you use ? You can join the discussion : https://github.com/easyphp/DEVSERVER/discussions and tell us what you need. @Chealer @hamza1886

**Comment by Chealer** [comment]
I [reported this against the website](https://github.com/easyphp/WEBSITE/issues/17).

**Comment by easyphp** [comment]
Xdebug version will specified on the website now.
