### ISSUE TITLE
Devserver 16.1.1 now fails as McAfee is quarantining a file

### ISSUE THREAD

**Issue by maggsweb** [easyphp/easyphp-devserver#122]
I've been using DevSever 16.1.1 for ages quite happily with McAfee, but now suddenly McAffee has decided that ePHPdev16 has a virus and quarantines an .exe file.  I've seen other historical posts relating to this and the solution has been 'upgrade to dev17'.
I've spent far too long today upgrading to 'dev17' and trying to get Virtual Hosts to work.  It's not working for me.  I'm not a complete novice either - I've gone through this process before upgrading from dev14 to dev16...
My (temp) solution is to turn of McAfee scanning.. ..but that's not sustainable, and upgrading to a new version with issues is also not a solution.
I'm looking for any ideas...

**Comment by abdfahim** [comment]
I actually am facing the similar issue with Dev17 where the antivirus is blocking the program due to possible threat PSKill

![image](https://user-images.githubusercontent.com/15644704/33224127-5cb32fd2-d1ba-11e7-819d-4aa425bcd9d9.png)

**Comment by maggsweb** [comment]
I resolved this eventually by adding the following to the Excluded files list.

![screenshot 2017-11-25 16 32 16](https://user-images.githubusercontent.com/196674/33232435-38ad4264-d1fe-11e7-89e8-d7fc7add2db8.png)
