### ISSUE TITLE
403 Forbidden: Client can not access to alias directory on local network 

### ISSUE THREAD

**Issue by atakanau** [easyphp/easyphp-devserver#124]
I created an alias directory called "my_alias". I connect to the local network with a cell phone. I accessed the root directory with the phone, but I could not access the alias directory.

"my_alias" setup | Root directory | "my_alias" directory
--- | -- | -- 
<img src="http://i.imgur.com/9VRzzjb.png" width="100%"/> | <img src="http://i.imgur.com/16e16tx.png" width="100%"/> | <img src="http://i.imgur.com/hnJXRAa.png" width="99%"/>

The following changes need to be apply to resolve this issue:

> EasyPHP-Devserver-17\eds-binaries\httpserver\apache[...]\eds-app-actions.php:117

```
if ($alias_serialized != '') {
	foreach (unserialize($alias_serialized) as $key => $alias) {
		$alias_link = str_replace("\\","/", urldecode($alias['alias_path']));
		$alias_link = str_replace("//","/", $alias_link);
		if (substr($alias_link, -1) == "/"){$alias_link = substr($alias_link,0,strlen($alias_link)-1);}
		$store_alias .= "Alias \"/";
		$store_alias .= $alias['alias_name'];
		$store_alias .= "\" \"";
		$store_alias .= $alias_link;
		$store_alias .= "\"\r\n";
		$store_alias .= "<Directory \"$alias_link\">\r\n";
		// $store_alias .= "\tOptions FollowSymLinks Indexes ExecCGI\r\n";
		// $store_alias .= "\tAllowOverride All\r\n";
		// $store_alias .= "\tOrder deny,allow\r\n";
		// $store_alias .= "\tAllow from 127.0.0.1\r\n";
		// $store_alias .= "\tDeny from all\r\n";
		// $store_alias .= "\tRequire all granted\r\n";			
		$store_alias .= "\tOptions Indexes FollowSymLinks MultiViews\r\n";	// +++
		$store_alias .= "\tRequire all granted\r\n";				// +++
		$store_alias .= "</Directory>\r\n";					// +++
	}
}

```

> EasyPHP-Devserver-17\eds-binaries\httpserver\apache[...]\conf\httpd.conf:57
```
# Change this to Listen on specific IP addresses as shown below to 
# prevent Apache from glomming onto all bound IP addresses.
#
#Listen 12.34.56.78:80
#Listen 127.0.0.1:80
Listen 80
```

... and result:
<img src="http://i.imgur.com/4jrpNn8.png"  width="33%"/>

**Comment by easyphp** [comment]
You need to use the module "Phone".
