### ISSUE TITLE
can't install devserver in windows 10

### ISSUE THREAD

**Issue by dnalexxio** [easyphp/easyphp-devserver#129]
Hi,
i have the problem that appears in your faq

System Error : "The program can't start because MSVCR1xx.dll/MSVCP1xx.dll/VCRUNTIME1xx.dll is missing from your computer. Try reinstalling the program to fix this problem"

Visual C++ Redistributable for Visual Studio 2015 package will not install because i have the 2017 version. 
i tried uninstalling 2017 redistributable package and installing 2015, but nothing changes. 

i do have the msvcr110.dll in some path of my pc, but devserver cannot find it. i also tried to put the file in the devserver installed folder, but the error remains. 
i tried reinstalling webserver and devserver many times but without solving.  

Can you please help me?

**Comment by REJack** [comment]
I use for any redistributable's a complete installer from sereby [AIO Runtimes](https://www.computerbase.de/downloads/systemtools/all-in-one-runtimes/)
