### ISSUE TITLE
[PrestaShop] Fatal error in module EDImport: Can't use function return value in write context

### ISSUE THREAD

**Issue by rp-lemaire** [easyphp/easyphp-devserver#134]
Hello, I'm a shop keeper, not a coding mogul ... and I'm stuck !

I downloaded EasyPHP DevServer-14.1VC9 (PHP 5.4.24)+ Prestashop 1.6.0.5 from :
>>> http://www.easyphp.org/save-easyphp-devservervc9+prestashop-latest.php 

I know it's not the latest version of PHP or EasyPHP, but that's the bundle... and I don't know how to upgrade it, or if the Prestashop boutique will still run on my localserver ...

It worked fine until I tried to install a migration module to pick up all the info from my source / old e-shop (Prestashop 1.4.10.0) and migrate it to my brand new target shop (PS 1.6.0.5)
The module is MigrationPRO - a well famed migration module. But which ever way I try to install it, it fails !
I've tried :
1) Adding the module V3.2.0 for PS1.6.1 (which they recommanded, although I run PS 1.6.0.5 ...)
>>>a) via the "Add a new module" button in the top-right corner (I chose the zip archive) : FAIL
>>>b) via the "Install" button to the right of the module name in the module list : FAIL
>>>c) manually (drag & drop) in the folder "C:/Program Files (x86)/EasyPHP-DevServer-14.1VC9/modules/prestashopmodules" (I dropped the unzipped folder, of course !) : FAIL

2) Adding the module V3.2.0 for PS1.6.0 (which they DID NOT recommand, although I run PS 1.6.0.5 ...)
>>>a) via the "Add a new module" button in the top-right corner (I chose the zip archive) : FAIL
>>>b) via the "Install" button to the right of the module name in the module list : FAIL
>>>c) manually (drag & drop) in the folder "C:/Program Files (x86)/EasyPHP-DevServer-14.1VC9/modules/prestashop/modules" (I dropped the unzipped folder, of course !) : FAIL

What else can I try ?!?
I really need your help here ...

**Comment by REJack** [comment]
Did you got some error messages or an Internal Error?

**Comment by rp-lemaire** [comment]
I got the error message in the title when I tried to go back to my prestashop backoffice in the module section
and the message goes away when I remove the migrationpro module folder from the prestashop directory (or folder) ...
I've tried to install another module and it worked just fine ... I don't understand why this one doesn't work

**Comment by rp-lemaire** [comment]
Thanks for your help ...

**Comment by REJack** [comment]
Oh ok.
Try to contact the module author, maybe he can help you with that, sorry.



> b) via the "Install" button to the right of the module name in the module list : FAIL

PrestaShop needs curl, this can be fixed, install curl on your system, I've used this installers from [this page](http://www.confusedbycode.com/curl/).

**Comment by julienduthoit** [comment]
Hi @rp-lemaire , Did you succeed to resolve your problem? I'm having the same error with this module.

Thanks

**Comment by julienduthoit** [comment]
Actually, I was installing migrationpro instead of migrationproserver (download link in the module) on the 1.6 source. Solved for me.

**Comment by rp-lemaire** [comment]
I switched to Xamp 5.6
I think that's what saved me ...
Hope you find a solution too
Regards 
Régis L
