### ISSUE TITLE
Dashboard inaccessible - Devserver unusable due to MSVCR110.dll, despite VC14 install

### ISSUE THREAD

**Issue by Chealer** [easyphp/easyphp-devserver#135]
As reported in ticket #32 , when installing Devserver (version 17.0) without the 32-bit Visual C++ Redistributable for Visual Studio 2012 (VC11), Devserver is unusable. Trying to open the dashboard causes an error with a message referring to MSVCR110.dll.

This happens on Windows 10 even if VC14 32-bit and 64-bit, as well as the 32-bit and 64-bit Visual C++ 2010 redistributables, the Visual C++ 2005 redistributable and the 64-bit VC11 are installed.

**Comment by hapicc1** [comment]
Try installing this, it works for me with the same issue.
https://www.microsoft.com/en-us/download/confirmation.aspx?id=30679

**Comment by abhijithmoody** [comment]
having the same issue on windows 10 , worked perfectly on windows 7

**Comment by cnaudes** [comment]
Hi all,

I'm having the same issue with Windows 10. I tried to install severall version of visual C++ redistributable and older version of Easyphp and the same problem occurs all the time.
The dll exists but Nothing works to fix the problem.

Any idea?
Thanks!

**Comment by Chealer** [comment]
Why was this ticket closed?

**Comment by Chealer** [comment]
@easyphp why is this ticket closed?

**Comment by Chealer** [comment]
@easyphp can you reopen this ticket?
