### ISSUE TITLE
Brand new install, nothing but errors.

### ISSUE THREAD

**Issue by vrdriver** [easyphp/easyphp-devserver#145]
Hi guys.
I just downloaded the latest version of your software 17.0. 
This is the first time I've never tried it before, so first time installation.

After it ran, I tried to start all servers and got the following error multiple times:

PHP Startup: bz2: Unable to initialize module
Module compiler with module API=20131226
PHP compiler with module API=20121212
These options need to match

Followed by heaps more errors, where eventually, no server actually started up.
I thought I'd let you know.

Windows 10 Pro x64.

**Comment by REJack** [comment]
Look at #84, this should help you.

**Comment by vrdriver** [comment]
Apologies. I feel like dill. Thanks.
