### ISSUE TITLE
Adware detected in Devserver 17

### ISSUE THREAD

**Issue by abdfahim** [easyphp/easyphp-devserver#146]
I can't start the dev server because my antivirus is blocking the following file.

![image](https://user-images.githubusercontent.com/15644704/33223936-c7302a1a-d1b8-11e7-91a1-06922cb22b95.png)

**Comment by Mlocik97-issues** [comment]
It's false alarm

**Comment by abdfahim** [comment]
Never received this with DevServer 14. Would be nice if fixes are applied to avoid this false alarm.

**Comment by gogol1402** [comment]
When launched, easyphp 17 is stopped by my antivirus "HitManPro.Alert". One process is considered "malicius" and the program does not allow me to operate. I had the same problem with easyPHP ver. 16, never had it with ver. 14. Problem is I need a higher version of the PHP component (at least PHP 5.6) which is not available on ver. 14. Any suggestions?
