### ISSUE TITLE
Virtual Host 1.8 on DevServer 17

### ISSUE THREAD

**Issue by Shaazaam** [easyphp/easyphp-devserver#147]
I am running Virtual Host 1.8 with DevServer 17 on a Windows 10 machine and have run into a few issues.

First when I create a new virtual host, it never shows up in the dashboard. I can confirm it exists by looking at my httpd-vhosts.conf and store_vhosts.php, as well as receiving a "this hosts exists" if I try to add it again. These are all local files.

Additionally I keep getting DNS errors when attempting to connect to one of my virtual hosts. I have followed documentation outlined [here](http://www.easyphp.org/documentation/devserver/getting-started.php) and [here](http://www.easyphp.org/documentation/devserver/virtual-hosts-manager-for-devserver.php). Nothing exists in my hosts file that would conflict with my local address.

**Comment by Shaazaam** [comment]
Update

It seems the root of the issues above is Windows hosts file can't be in read-only mode, which makes sense. While an experienced developer may figure this out, this type of behavior is not outlined in any of your documentation. Windows leaves this file in read only mode by default for security reasons, so an novice user would never think to take it out of read only mode.

**Comment by funkman733** [comment]
Hi, I have the same issue.
What have you do to solve it?

**Comment by Shaazaam** [comment]
> Hi, I have the same issue.
> What have you do to solve it?

If you're running Windows, go to your hosts file located in C:\windows\system32\drivers\etc. Ensure this file is not in read only mode, and also ensure your user have permissions to write to this file. You can check this in the Security tab. See below.

![image](https://user-images.githubusercontent.com/6669004/54073180-0e872480-4252-11e9-8684-2fe2b78e6559.png)

![image](https://user-images.githubusercontent.com/6669004/54073196-3bd3d280-4252-11e9-80e9-2194a6c04c3e.png)
