### ISSUE TITLE
Virus HideExe

### ISSUE THREAD

**Issue by bkraut** [easyphp/easyphp-devserver#151]
When downloading PHP 5.4 for DevServer 16.1 an HideExe virus was detected and I could not install PHP.
What is this?

**Comment by bkraut** [comment]
![untitled-1](https://user-images.githubusercontent.com/1028053/34944213-0e2efcf2-f9ff-11e7-8253-30b8891e7ddb.jpg)

**Comment by easyphp** [comment]
This a false positive.
