### ISSUE TITLE
Can't start HTTP or DB server

### ISSUE THREAD

**Issue by EnlightenedOctopus** [easyphp/easyphp-devserver#155]
Hi,
I've installed EasyPHP 17.0 on Windows 10, but when i go to my dashboard it displays an error message:
Notice: Undefined offset: 3 in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-dashboard\index.php on line 18

Notice: Undefined offset: 3 in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-dashboard\index.php on line 23

and when i try to start eithe the HTTP or DB server it just reloads and apparently does not start the server. I've tried uninstalling and reinstalling but it doesn't work.
i've tried installing the 16.1 version it doesn't diplay an error message but the HTTP server can't seem to start either
in advance thanks for the help

**Comment by Elnopelado** [comment]
https://github.com/easyphp/easyphp-devserver/issues/112  (Solucionado)
