### ISSUE TITLE
My apache (http server) won't launch but my database works correctly

### ISSUE THREAD

**Issue by Ballzygrim** [easyphp/easyphp-devserver#165]
Hello !
On my administration page, my apache (http server) refuse to start, but my database base can be launched correctly.
I tried to change the port number (80 to 8080) and change this number into my httpd.conf, launched easyphp as the administrator etc but nothing seems to work. 

Thank you

**Comment by elisspace** [comment]
I'm running into the same issue. I haven't touched the program in about two weeks and then upon coming back today the webserver won't launch but the database works just fine. Maybe related: the logs for the webserver are not showing any information for any actions I try to do today; they stop back back on the date I last used it successfully. 

I've tried running as administrator, changing ports, and changing the version of PHP. The only thing that worked very a short time was restarting the computer, but the server only ran for a few minutes before it refreshed(?) and no longer could be started.
