### ISSUE TITLE
paid for subscription but cannot log on to warehouse

### ISSUE THREAD

**Issue by kilvroch** [easyphp/easyphp-devserver#166]
I have paid for a subscription and received an email with my login and password.
However, when I try to log on from firefox or chrome, it tells me "Email address and/or password invalid"

**Comment by easyphp** [comment]
Can you send an email to warehouse@easyphp.org? We need your email address to check.

**Comment by kilvroch** [comment]
thank you, my login issue has now been solved. (my login does not use 
this email address, it uses another)
