### ISSUE TITLE
EasyPHP Devserver 17.0 doesn't create password and privileges for new account

### ISSUE THREAD

**Issue by majixd** [easyphp/easyphp-devserver#168]
I want to use new EasyPHP release Devserver 17.0 for PHP sites. After installation of EasyPHP I opened phpMyAdmin page and tried to create a new account with my own password and full privileges. The account created but with no password and privileges. I have tested it on two different PCs with Windows 7 and 10 . But the problem persists . what is the reason ?

**Comment by LavioPareschi** [comment]
The same happens to me. Using Devserver 17 as well.
I have a database and a user account with password. So, I go to PhpMyAdmin to import the database and to set a new user account WITH password.  It opens the form, I enter the user name, the host, the password, privileges .... and GO.
But the password is ALWAYS blank. No way to add a password in PhMyAdmin.
Thus, I cannot use Devserver to run and test my site locally without setting the password blank.

By the way... I already have a EasyPHP 14 installation I use to do my stuff and it works fine, with all user accounts WITH paswords created using PhpMyAdmin.
But in Devserver 17 phpmyadmin does not create passwords except blank ones.
