### ISSUE TITLE
Devserver installed and doesn't work - no uninstall???

### ISSUE THREAD

**Issue by mark1502** [easyphp/easyphp-devserver#170]
I tried to install Devserver on a new Win 7 32 bit vm.  The install completed fine, but nothing worked and I got an error message when trying to open the dashboard.  Apparently a needed microsoft dll was missing.  After searching around on the internet, I found the message of another person who had the same problem with Devserver and he posted the link to the needed dll.

After installing the missing dll, the error message went away, but still the servers wouldn't work.  So, I just decided that I'd uninstall Devserver.  But it won't be that easy.  Because there is no uninstall option!  Really??

I'm disappointed about the thing not working.  But worse, now I have to figure out how to remove this crap.

So, here are two "issues" regarding Devserver.  1. Include all of the needed dlls (or provide links to download, if needed).  2.  The Devserver installation needs an UNINSTALL feature which should remove everything and reset anything changed by the install.

**Comment by Lokotito** [comment]
Just delete the DEVSERVER folder (where you installed devserver), thats all.
Devserver need MS VC runtime to work, not simple dll.
