### ISSUE TITLE
php_pdo_pgsql.dll - The specified module could not be found.

### ISSUE THREAD

**Issue by gt1202** [easyphp/easyphp-devserver#171]
php_pdo_pgsql.dll - The specified module could not be found.

Why does this happen? Tried with several php 7 versions.

**Comment by easyphp** [comment]
Any error message ?
Can you give us a copy of php.ini ?

**Comment by F4LK0N** [comment]
I have the definitive solution!!!

Add the path of the PHP folder to the Windows System Paths Variable 
(Right click on 'My Computer' > 'Properties' > 'Advanced System Settings' > 'Environment Variables')

Restart the computer.
