### ISSUE TITLE
phpmyadmin open button error page

### ISSUE THREAD

**Issue by Giulo77** [easyphp/easyphp-devserver#174]
Hi,
i've installed devserver 17 about 6 months ago and works well, but last day into dashboard I can't see database from open button phpmyadmin. I've try two version of this program but nothing to do.
I've try to reinstall all software with last version of php, mysql and works but when I replace database and edit all ini files it stop to works.
I can use cmd mysql but with a difference: for example on another server installation  iìI can access to db with command mysql -u root and on first server I obtain access denied then I must use option -P 3306
It's incredible, all ini files are the same...one is win 7 64 bit and other win server 2016 where I have the error page.

**Comment by easyphp** [comment]
MySQL server is running well ? Any error message ? Try to kill all processes and restart everything.

**Comment by Giulo77** [comment]
If i restart pc it's not the same that kill and restart services? My web application works very well without problems. Where i've to see for any errors?
