### ISSUE TITLE
Unable to auto start servers on EasyPHP Devserver 17.0

### ISSUE THREAD

**Issue by arielss17** [easyphp/easyphp-devserver#175]
Hello!

Even if check the boxes in the dashboard, the Apache and MySQL servers are not auto starting.
I have to click on "Start all servers" every time.

Using Windows 10 Enterprise.

Already checked the eds.ini file:

[eds]
Version=17.0
Serie=17
Lang=en
Autostart_httpserver=1

Autostart_dbserver=1

**Comment by easyphp** [comment]
Hi
It's normal for Devserver 17. The servers start automatically when you open the dashboard, not when you start Devserver.
We will change that with Devserver 19.

**Comment by arielss17** [comment]
Even when I open the dashboard, I have to click "Start" in each of the servers.

**Comment by easyphp** [comment]
Hi
Did you find a solution ?
