### ISSUE TITLE
New users get very bad experience.

### ISSUE THREAD

**Issue by Jopm17** [easyphp/easyphp-devserver#176]
So I downloaded Devserver 17 and did a new install following the instructions as any new user would since I needed a WAMP server. 
Started EasyPHP, and did Servers, Start All Servers and all I get is error after error.
Some are in the attached pdf. 

All I expect is that the fresh, free download will install and work, surely that's not much to ask? It certainly puts one off EasyPHP big time. 
I looked on the website and it suggested updates could help but then it appears you have to pay to download the updates. So why advertise as free when it isn't? It's just how to lose users quickly.
After all, there's plenty of other free WAMP servers around so if this EasyPHP doesn't work, I'll throw it away and use another product. 

[Devserver errors.pdf](https://github.com/easyphp/easyphp-devserver/files/3158321/Devserver.errors.pdf)

**Comment by easyphp** [comment]
It's free. You can find free updates on https://warehouse.easyphp.org.
If you have those errors it's because you already have a PHP version in your PATH. Everything is explained in the "support" section.

**Comment by Jopm17** [comment]
It was a clean install! No PHP present.
"_Everything is explained in the "support" section_."
Exactly where? 
All I get is this page or StackOverflow or a similar page with loads of discussion comments. Nothing straightforward to follow.

**Comment by easyphp** [comment]
Did you check your PATH?

**Comment by Jopm17** [comment]
I did and it only has Windows and SQL Server paths.
There is no documentation on your support that suggests doing that or telling a new user how to do that.
