### ISSUE TITLE
Dashbord unrecheable 

### ISSUE THREAD

**Issue by CyrilCharlier** [easyphp/easyphp-devserver#178]
Hi,

after un good installation of DevServer 17 and all update on WareHouse, when i try to go to "127.0.0.1:1111" with a right click and "Open Dashboard", i can't open this site "127.0.0.1:111", it is unrecheable.

In an other hands,  "eds-httserver.exe" on port 80 and "eds-dbserver.exe" on port 3306 it is OK.

An idea ? 

thanks

**Comment by easyphp** [comment]
Strange. Any PHP version in the Windows PATH ? Check the processes and kill any console or php exe. Reboot ?

**Comment by CyrilCharlier** [comment]
In Windows Path : one PHP version i will use in CMD for symfony project.

but, after third reboot it is ok. No install or update. Only lunching DevServer after each reboot
