### ISSUE TITLE
System Event Table Issue - Repair Fails?

### ISSUE THREAD

**Issue by WebSpectrum** [easyphp/easyphp-devserver#182]
Keeping getting this: Cannot proceed because system tables used by Event Scheduler were found damaged at server start

Repaired MySQL and still get it

**Comment by easyphp** [comment]
We need more information.

**Comment by WebSpectrum** [comment]
MySQL 5.7.17 x86  ERROR: 'Cannot proceed because system tables used by Event Scheduler were found damaged at server start'

Tried this but it failed to fix/repair event table:
mysqlcheck -u root -p --all-databases --check-upgrade --auto-repair
mysql_upgrade -u root -p

I updated to MySQL 5.7.24 x86 and all OK now so maybe an issue with the MySQL 5.7.17 x86 bundled build?
