### ISSUE TITLE
Dashboard Devserver (17 and 16) not opening on my new laptop

### ISSUE THREAD

**Issue by alotfi06** [easyphp/easyphp-devserver#186]
Hello,

I try to install Easyphp Devserver on my new laptop (Windows 10, 64 bits) and i never succeed to open the dashboard.
At the beginning i had an eds-dashboard.exe error because it was missing the MSVCR110.dll
After installing the dll (i downloaded it from the net) 
=> When i try to open Dashboard => eds-dashboard.exe error => 0xc000007b
I tried multiple solutions (install all the package visual c++ from 2008 to 2015-2019, X86 and X64)
I tried to use the lodctr/r command on the Windows Supershell
But still the same error (V17 or V16) : => When i try to open Dashboard => eds-dashboard.exe error => 0xc000007b
I tried to install as an admin and to open as an admin same error.

Please i need help.
It s a new laptop Asus vivobook win 10. Is it possible that i have a hardware problem ?

**Comment by klodoma** [comment]
Same here! Similar issue. Maybe related. 
![Screenshot_433](https://user-images.githubusercontent.com/944350/61461503-19c12e00-a971-11e9-8bc9-d1ac3306d358.png)

**Comment by schoemberger** [comment]
Install the Visual C ++ Redistributable Package. The x64 version did not work in my case, so I installed x86 and that's it.

**Comment by klodoma** [comment]
I can confirm that installing the Visual C++ Redistributable for Visual Studio 2012 x86 version fixed the problem. Installing the x64 version didn't worked.
