### ISSUE TITLE
Start on start-up not working

### ISSUE THREAD

**Issue by codestylist** [easyphp/easyphp-devserver#188]
I use Devserver 17. Under Startup Settings I have checked both options to start the servers on start-up. Unfortunately this is not working. Not when I Easyphp Devserver nor wehn I open the dasboard. So, I allways have to start the server manually.
I found out the feature "Start / Restart All-Servers", from the trayicon,  does not work either.
Any suggestions what can happen or how I can check the reason for this behavior?

**Comment by cyril-fsm** [comment]
maybe this solution will suit you : https://github.com/easyphp/easyphp-devserver/issues/189#issuecomment-710130866
