### ISSUE TITLE
msvcr100.dll missing error

### ISSUE THREAD

**Issue by samdeesh** [easyphp/easyphp-devserver#19]
Even after installing vcredlist (Microsoft visual c++ redistributable ) I am getting this error
![image](https://cloud.githubusercontent.com/assets/8951753/11959259/597ac4d0-a8f2-11e5-9f92-d4ccd1d3bd5a.png)

I installed both x64 & x86 but still same issue
![image](https://cloud.githubusercontent.com/assets/8951753/11959230/39a33048-a8f2-11e5-8c2c-633155b80d83.png)

**Comment by nono1988** [comment]
i am facing same issue

**Comment by easyphp** [comment]
Hi
MSVCR110.dll is the Microsoft Visual C++ Redistributable dll that is needed for applications built with Visual Studio 2012, like PHP and Apache.
This error appears when Microsoft Visual C++ Redistributable 2012 is not already installed on your system. The redistributable can easily be downloaded and installed.
Please, have a look at "Requirements" on http://www.easyphp.org/easyphp-devserver.php.
