### ISSUE TITLE
EasyPhp Devserver 17 infected with IDP.Generic?

### ISSUE THREAD

**Issue by Gueguen003** [easyphp/easyphp-devserver#191]
Hello,
I work with Windows 8.
I just installed EasyPhp Devserver 17.
I can't launch the dashboard, the Avast antivirus block it and display the message : "Nous avons bloqué eds-dashboard.exe car le site est infecté par IDP.Generic - Détection de la ligne de commande".
Avast put the file into quarantine, and it's no more possible to launch eds-dashboard.exe.
Is really eds-dashboard.exe infected with IDP.Generic?
Is it a false positive?
(I don't write often in english, perharps some mistakes can remain in the text).
Regards,

**Comment by Schonke26** [comment]
Hi,
I had the same problem on Windows 10. It's an Avast bug on Windows and, on my system, Avast didn't even block infected program.
The only way I've found is to stop all Avast agents (right click on Avast program, click on "Gestion des agents Avast" and choose "Désactiver pour 10 minutes"), then start devserver, try to Open Dashboard (it must work), then you can restart Avast agents.
You can also try to start devserver on Windows start. If it starts before Avast, it must also work. But I didn't try.
Hope it helps.
Regards

**Comment by Stoi84** [comment]
I'm experiencing the same issue since today. I reported the false positive to Avast.

**Comment by Gueguen003** [comment]
Hi,
I finally declare EasyPhp Devserver 17 as an exception for Avast since I recevied several suggestions  which dealt with this issue.
Thank you all for your help.
Regards

**Comment by Stoi84** [comment]
I'm curious what exceptions worked for you. I tried everything, and the only thing that worked for me is to completely disable the behavior shield, exceptions did not help.
