### ISSUE TITLE
projectname.local refused to connect

### ISSUE THREAD

**Issue by Debongot** [easyphp/easyphp-devserver#194]
I'm already start the easyphp devserver and VirtualHostsManager-1.8 but the project is will not open. it refusing to connect. why? but last few days it works. this module is virtual host manager.

![2020-01-27_10-28-46](https://user-images.githubusercontent.com/51074980/73147215-72783d00-40f1-11ea-92d8-09724528fcc0.png)

**Comment by easyphp** [comment]
Any logs ? What's your httpd.conf ?
