### ISSUE TITLE
EasyPhp Devserver - Cannot Load The Dashboard

### ISSUE THREAD

**Issue by atilav** [easyphp/easyphp-devserver#195]
Hi guys,

I tried everything, but still cannot load/open the dashboard.

Installed Easyphp...
- run as administrator - nothing
- change the ports in the http.conf(apaches server dir) file to 81 or 85 or 8887 - again nothing
- created a bat file with the following: but nothing
```
eds-dashboard.exe -S 127.0.0.1:1111 -c eds-dashboard.ini
cmd /k
```

can anyone help with this?

**Comment by easyphp** [comment]
Any error message ? logs ?

**Comment by WisTex** [comment]
I had a similar problem. The dashboard would not load. I noticed that there were two Devserver icons in the Windows icon tray. I tried to exit them using the menu, but they did not close. I opened Windows Task Manager and started killing the Aeston Tray Menu, Apache HTTP Server and something else. I restarted Devserver and the Dashboard appeared, Not sure if that was the same problem the original poster had, but that is what solved it in my case.

**Comment by milos12345** [comment]
Same here. I can open http://127.0.0.1/phpinfo.php to see that Apache is working. 
I have tried changing dbport port in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\dbserver\mysql5717x86x200501114816 to 3308
same issue. 
The mysql_error.log shows:

> 2020-05-01T16:29:35.341307Z 0 [Warning] TIMESTAMP with implicit DEFAULT value is deprecated. Please use --explicit_defaults_for_timestamp server option (see documentation for more details).
> 2020-05-01T16:29:35.345310Z 0 [Warning] 'NO_ZERO_DATE', 'NO_ZERO_IN_DATE' and 'ERROR_FOR_DIVISION_BY_ZERO' sql modes should be used with strict mode. They will be merged with strict mode in a future release.
> 2020-05-01T16:29:35.345310Z 0 [Warning] 'NO_AUTO_CREATE_USER' sql mode was not set.
> 2020-05-01T16:29:35.345310Z 0 [Note] --secure-file-priv is set to NULL. Operations related to importing and exporting data are disabled
> 2020-05-01T16:29:35.353309Z 0 [Note] C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\dbserver\mysql5717x86x200501114816\bin\eds-dbserver.exe (mysqld 5.7.17) starting as process 23040 ...
repeating with just different process number

**Comment by rk0ldskullj** [comment]
> I had a similar problem. The dashboard would not load. I noticed that there were two Devserver icons in the Windows icon tray. I tried to exit them using the menu, but they did not close. I opened Windows Task Manager and started killing the Aeston Tray Menu, Apache HTTP Server and something else. I restarted Devserver and the Dashboard appeared, Not sure if that was the same problem the original poster had, but that is what solved it in my case.

**Comment by EleniaB** [comment]
Hello folks
When I tried in a command window the line

I saw the problem

C:\Users\jelenia>"C:\EasyPHP-Devserver-17\eds-dashboard\eds-dashboard.exe" -S 127.0.0.1:1111 -c eds-dashboard.ini
PHP 5.6.26 Development Server started at Wed Oct 14 10:41:26 2020
Listening on http://127.0.0.1:1111
Document root is C:\Users\elenia <------- PROBLEM HERE
Press Ctrl-C to quit.

Need to force the document root
the command "eds-dashboard --help" to show the usefull option 

Then edit the run-devserver.init and complete the 11 line

Action: run; FileName: "eds-dashboard/eds-dashboard.exe"; WorkingDir: "eds-dashboard"; Parameters: " -S 127.0.0.1:1111 -c eds-dashboard.ini **-t EasyPHP-Devserver-17\eds-dashboard\**"; ShowCmd: hidden

just adding the -t option with the good document root folder

And now the dashboard works fine

**Comment by Chaprnks** [comment]
I'm having a similar issue. I can't seem to get port 1111 to work for the life of me. Doesn't show up on the port controller app, or process hacker network tab. After trying your command prompt method, I gained a clue:

![dYr5Ufn](https://user-images.githubusercontent.com/6340970/98434557-d4150100-209e-11eb-9645-a36f58562d75.png)
`Failed to listen on 127.0.0.1:1111 (reason: An attempt was made to access a socket in a way forbidden by its access permissions.`

Ironically, after trying to modify the command to use port 2222, it works completely fine!
`eds-dashboard.exe -S 127.0.0.1:1111 -c eds-dashboard.ini`

What I find extremely strange, is that there aren't any other programs using port 1111 & that error message was very vague.. Hopefully this may help others (as its kept me up all night pulling my hair out)

**Comment by Chaprnks** [comment]
Update: So it appears that the cause was Hyper-V/Virtual Machine Platform; which was required to get WSL 2 (Subsystem for Linux) working. Somehow it mysteriously uses the port 1111. As soon as I disabled the features from "windows features" tab & rebooted.. easyphp dashboard immediately showed up after a single launch with the default port 1111

Long story short, the only way to use both WSL 2 & EasyPHP is to use a different port than 1111 for its dashboard.

**Comment by A-Ghacker** [comment]
I'm facing the same error while loading the Devserver Dashboard and it tells that it can't be loaded , is there any solution for this ? 
I've tried everything but still same error
