### ISSUE TITLE
Will EasyPHP run with Vicual C++ 2017?

### ISSUE THREAD

**Issue by yawn-g** [easyphp/easyphp-devserver#196]
I don't want to remove 2017 to install 2015. Is there another way? Is it possible to download the missing dll from a safe place? I have been unable to use any version of EasyPHP on Windows 10 :(

Thanks!

**Comment by easyphp** [comment]
Yes, sure. Please go to the FAQ : https://www.easyphp.org/faq_devserver.php

**Comment by yawn-g** [comment]
That is not answering my question. Have *you* read the faq?

**Comment by yawn-g** [comment]
Just to let you know, and if somebody else is running into a similar problem, xampp works just fine. Also, please read the FAQ instead of just pointing to it. Thanks.
