### ISSUE TITLE
Warning HTTP Server

### ISSUE THREAD

**Issue by zerealpolo** [easyphp/easyphp-devserver#205]
Hello,
so far i have been using Devserver 14.1 VC11. I installed recently Devserver 17.0. 

Starting the HTTP Server, the following message is displayed  

> Warning
> PHP Startup: bz2: Unable to initialize module
> Module compiled with module API=20131226
> PHP  compiled with module API=20121212
> These options need to match

I've got a 64-bit OS with Win7 and the Visual C++ studio 2015...

How can I solve this ?

**Comment by easyphp** [comment]
It seems that an older version of PHP is in your Windows PATH. Edit the PATH and remove all PHP versions found in the PATH.
