### ISSUE TITLE
 PhpMyAdmin 5.0.1 module updated

### ISSUE THREAD

**Issue by SantinoITC** [easyphp/easyphp-devserver#206]
Ciao, ho installato EasyPHP Devserver 17.0 ...
ho aggiornato il modulo di PhpMyAdmin 5.0.1... quando utilizzo la funzione esporta schema dalla sezione Designer mi da questo errore...

Fatal error: Uncaught TypeError: ucfirst() expects parameter 1 to be string, null given in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-modules\phpmyadmin501\libraries\classes\Plugins\Schema\Pdf\Pdf.php:272 Stack trace: #0 C:\Program Files (x86)\EasyPHP-Devserver-17\eds-modules\phpmyadmin501\libraries\classes\Plugins\Schema\Pdf\Pdf.php(272): ucfirst(NULL) #1 C:\Program Files (x86)\EasyPHP-Devserver-17\eds-modules\phpmyadmin501\vendor\tecnickcom\tcpdf\tcpdf.php(3560): PhpMyAdmin\Plugins\Schema\Pdf\Pdf->Header() #2 C:\Program Files (x86)\EasyPHP-Devserver-17\eds-modules\phpmyadmin501\vendor\tecnickcom\tcpdf\tcpdf.php(3227): TCPDF->setHeader() #3 C:\Program Files (x86)\EasyPHP-Devserver-17\eds-modules\phpmyadmin501\vendor\tecnickcom\tcpdf\tcpdf.php(3139): TCPDF->startPage('L', '', false) #4 C:\Program Files (x86)\EasyPHP-Devserver-17\eds-modules\phpmyadmin501\libraries\classes\Plugins\Schema\Pdf\PdfRelationSchema.php(493): TCPDF->AddPage('L') #5 in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-modules\phpmyadmin501\libraries\classes\Plugins\Schema\Pdf\Pdf.php on line 272

I've got a 64-bit OS with Win10 
How can I solve this ?

**Comment by easyphp** [comment]
Could you explain in English ?
