### ISSUE TITLE
Can't install EasyPHP

### ISSUE THREAD

**Issue by zeidbuljubasic** [easyphp/easyphp-devserver#215]
When i'm trying to install EasyPHP Devserver 17, i recieve error message "The system cannot find path specified"

Please help, thank you.

**Comment by easyphp** [comment]
Can you give us more information ?
First install?  OS version? When the error occurs (which step) ?

**Comment by zeidbuljubasic** [comment]
Thank You for response, i'm using windows 10, this is my first install

Error is occurs when i click on .exe installation file

**Comment by easyphp** [comment]
Can you try to delete the .exe and download it again ?

**Comment by zeidbuljubasic** [comment]
I was. I'm trying to reinstall my windows but error occurs again. I would like to use easyphp really. I'm finding solve for error more than 3 days so i decided to write here.

**Comment by easyphp** [comment]
Try to save your .exe in another folder (C:\Users\yourname for example). No need to reinstall Windows.

**Comment by zeidbuljubasic** [comment]
I was. Maybe there is some app for installing .exe files, or older version of devserver, i can't find same. If there is, You can send me older version.

**Comment by easyphp** [comment]
Windows 10 and Devserver 17 work fine together.
- delete "EasyPHP-Devserver-17.0-setup.exe"
- restart your computer
- download "EasyPHP-Devserver-17.0-setup.exe" again : https://www.easyphp.org/easyphp-devserver.php
- double-click on "easyphp-devserver.php"
- the setup should start

**Comment by zeidbuljubasic** [comment]
It is not working. PLease tell me what is differents beetwen devserver and webserver. Maybe webserver will be sufficient

**Comment by zeidbuljubasic** [comment]
can't install. btw, i find devserver 16 and it is working, he will do the work?

**Comment by zeidbuljubasic** [comment]
what is differents beetwen 17 and 16, is it huge?

**Comment by zeidbuljubasic** [comment]
Here is new problem, i was install devserver and i'm starting same. When i was start, here is error "The code execution cannot proceed because MSVCR110.dll was not found."

**Comment by easyphp** [comment]
Have a look at the FAQ and documentation (https://www.easyphp.org/documentation/devserver/). All this is explained.

**Comment by zeidbuljubasic** [comment]
1 more question. Can i update devserver 16 to 17 without uninstalling 16 and isntalling 17. By dashboard or something like that.

**Comment by zeidbuljubasic** [comment]
@easyphp . Thank you for help. I finded way. I move file to my flash drive and install it. It is working. You can close this case :D
