### ISSUE TITLE
When changing PHP version from 5.6.30 x86  to  7.1.3 x86, HTTP Server doesnot start. 

### ISSUE THREAD

**Issue by kuldeep1278** [easyphp/easyphp-devserver#218]
Working only for PHP_5.6.30x86. My system is Window 7 Ultimate.

**Comment by th3design** [comment]
i have the same Problem  Windows 10 Pro. Ownly php5.6.30 starts

**Comment by kressly** [comment]
I also had the same problem but I reinstalled and also I turned off the server before changing to 7.1.3

**Comment by samfourie** [comment]
> I also had the same problem but I reinstalled and also I turned off the server before changing to 7.1.3 and it is working

Is you windows 10/7 Installation up to date with all the VC runtimes?. I have found in the last with other WAMP servers that not having them installed with affect the successful startup of the PHP servers higher than PHP 5.6**

https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0
