### ISSUE TITLE
Memory error in DevServer 17.0 when accessing HTTP server settings from Dashboard page

### ISSUE THREAD

**Issue by SimonPatrick56** [easyphp/easyphp-devserver#220]
When trying to access HTTP server settings, I receive the following error message:

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 223972214 bytes) in C:\Program Files (x86)\EasyPHP-Devserver-17\eds-binaries\httpserver\apache2425vc11x86x170629145706\eds-app-dashboard.php on line 77

Has happened several times.

Operating system: Microsoft Windows 7 professional.

Many thanks,

Simon Patrick

**Comment by SimonPatrick56** [comment]
I have now reinstalled Devserver and was able to access the HTTP Server settings. A little worried that no-one replied to my post, even after a month.

**Comment by denischiron** [comment]
I've encountered this problem this morning and the solution was to delete the error.log from the httpserver/apacheXXX/logs folder.
Its size was larger than 600Mo.
