### ISSUE TITLE
Dashboard doesn't opening

### ISSUE THREAD

**Issue by zeidbuljubasic** [easyphp/easyphp-devserver#221]
I started Devserver 17 and opened dashboard by clicking icon in taskbar. I am in browser on 127.0.0.1:1111 but dashboard doesn't loading. I have message "This site can’t be reached"

Edit: Solved :)

**Comment by PierreLouisF** [comment]
Hey i have the same thing, wath is the solution ?

**Comment by zeidbuljubasic** [comment]
> Hey i have the same thing, wath is the solution ?

I just kill all process instances of devserver and start new from file location (C:/.../EasyPHP/devserver.exe)

I do not know file name but it is .exe file with devserver icon
