### ISSUE TITLE
phpMyAdmin continued "The mysqli extension is missing"

### ISSUE THREAD

**Issue by samfourie** [easyphp/easyphp-devserver#224]
I get a continued "The mysqli extension is missing" error not matter what i do. I have reinstalled AND downloaded all of the involved modules. the error continues to show up. I am on Windows 10. 

![Untitled-1_r2_c2](https://user-images.githubusercontent.com/6639868/110236490-c7b28f00-7f3e-11eb-856c-83a93fc75d65.jpg)

**Comment by easyphp** [comment]
Do you have any MySQL service or MySQL process running ? With CMD, check if you have mysql, php, apache or easyphp running, kill them and start again.
