### ISSUE TITLE
Useable versions of PHP

### ISSUE THREAD

**Issue by samfourie** [easyphp/easyphp-devserver#225]
I have subscribed and downloaded additional versions of PHP. They are not selectable from the "version to use" dropdown under settings. I have rebooted the pc and restarted the server several times still not more versions available than the two original php versions the server came with. Using windows 10 with all VC Runtimes updated and installed.

![Untitled-1](https://user-images.githubusercontent.com/6639868/110236703-f715cb80-7f3f-11eb-9bd2-f543f323e808.jpg)

**Comment by easyphp** [comment]
This is normal. For PHP x64 your need Apache x64. So, first, stop Apache, change to Apache x64 and then choose a PHP x64 version.

**Comment by samfourie** [comment]
Thank you
Sorted



*Sam FouriePhotographic Artist*

*Tel: 076 787 5800*


*Facebook - https://www.facebook.com/fourie1999
<https://www.facebook.com/fourie1999>Website - https://samfourie.co.za/
<https://samfourie.co.za/>Napier, Overberg, Western Cape, South Africa*

IMPORTANT: The contents of this email and any attachments are confidential.
They are intended for the named recipient(s) only. If you have received
this email by mistake, please notify the sender immediately and do not
disclose the contents to anyone or make copies thereof.
