### ISSUE TITLE
Devserver - no start/restart buttons

### ISSUE THREAD

**Issue by mnabialek** [easyphp/easyphp-devserver#23]
New release seems to be less functional than old one. In old one (14.1) there was nice and quick right menu - start/stop/restart and in new 16.1 version you need to manually start first web server (and you need to choose which one Apache or Nginx) and then MySQL server. It's quite time consuming. I would like to start last configuration out of the box and not running everything separately each time.

**Comment by Madebym** [comment]
@mnabialek +1 for this

Also, how should one uninstall 16.1 version? I would like to use the older 14.1, but don't see easy way of uninstalling.

**Comment by easyphp** [comment]
@mnabialek It will be implemented in the next version. We are working on it. It's on our TODO list.
@Madebym If you want to uninstall 16.1, see FAQ (http://www.easyphp.org/support.php)

**Comment by Madebym** [comment]
@easyphp Yep, I know that, but your accordion is not working on the support page. It always opens the same answer, the one for the missing .dll.

**Comment by easyphp** [comment]
Oups, sorry. Fixed now.

**Comment by Madebym** [comment]
Not a problem. Thanks !
