### ISSUE TITLE
Unable to use new EasyPHP-Devserver-16.1 installation - RiskWare.CHP malware detected

### ISSUE THREAD

**Issue by amigoaldo** [easyphp/easyphp-devserver#24]
After installing new  EasyPHP-Devserver-16.1(-setup.exe),
when I start Apache server my Malvarebytes antivirus blocks 
eds-app-lauch.exe
telling that RiskWare.CHP malware is detected.

![riskware_chp](https://cloud.githubusercontent.com/assets/3460433/12367013/4d4da61e-bbdf-11e5-91af-20a84ee8be46.jpg)

**Comment by amigoaldo** [comment]
I tried to use anywhere that file (eds-app-launch.exe) setting
Malvarebytes to "non check" for that file.
The Apache is started with a lot of "warning errors".
Error log attached.
Apache (httpd) seems  to work.
[error.txt](https://github.com/easyphp/easyphp-devserver/files/92679/error.txt)

Unable to start mysql. Error log is empty. Starting mysql from dashboard button seem do nothing.

By.
          Amigoaldo

**Comment by alanmazzilli** [comment]
Hi,
I'm having a issue that seems like this, but in my case, i have more detections.
below  i'm sending the images:
![primeira-deteccao](https://cloud.githubusercontent.com/assets/10810852/13175760/b7c5e194-d6f3-11e5-8415-3b3bc0720d27.png)
![segunda-deteccao](https://cloud.githubusercontent.com/assets/10810852/13175763/b7f15428-d6f3-11e5-8377-5021e3f7c607.png)
![todas-deteccoes](https://cloud.githubusercontent.com/assets/10810852/13175761/b7c6471a-d6f3-11e5-9ef9-2108d4661e15.png)
![ultima-tela](https://cloud.githubusercontent.com/assets/10810852/13175762/b7c6bd94-d6f3-11e5-9ebf-68023bde0a65.png)


---------------------------
Setup
---------------------------
Unable to execute file:
C:\Program Files (x86)\EasyPHP-Devserver-16.1\run-easyphp-devserver.exe
CreateProcess failed; code 2.
The system can not find the file specified.
---------------------------
OK   
---------------------------

**Comment by JamesFreezeCZ** [comment]
oh so i am not alone

 * RiskWare.CHP, C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-binaries\php\php5619vc11x86x161225071425\eds-app-launch.exe, , [b32fe4096c2ee35323f44875e320c63a]
 * RiskWare.CHP, C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-binaries\php\php704vc14x86x161225071425\eds-app-launch.exe, , [944e905d9cfeb284fc1b6855d231f10f]
 * RiskWare.CHP, C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-dashboard\eds-app-launch.exe, , [ce1417d63169a98ddb3c922b30d3eb15],

**Comment by ala-poubelle** [comment]
Symantec also detects it as a heuristic virus:
Filename,Risk,Action,Risk Type,Logged By,Original Location,Computer,User,Status,Current Location,Primary Action,Secondary Action,Action Description,Date and Time
"eds-app-launch.exe","Bloodhound.MalPE","Quarantined","Heuristic Virus","Auto-Protect scan","C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-binaries\php\php5619vc11x86x170324094848\","XXX","Infected","Quarantine","Clean security risk","Quarantine","The file was quarantined successfully.","27/03/17 10:08:51 AM"

**Comment by easyphp** [comment]
No worries. Those alerts are false positive. And it's fixed with the next version (Devserver 17).

**Comment by amilabandara** [comment]
Yes, I'm having the same issue. I use Mcafee and every time I started the dev server it quarantines EDS-APP-LAUNCH.exe and several similar named exe files.

**Comment by aryldo** [comment]
I have a similar problem with devserver  version 17 and ESET Endpoint Security
![image](https://user-images.githubusercontent.com/12472748/146549801-17c3b8e9-0759-4608-86aa-33d1bb1eb919.png)
