### ISSUE TITLE
Ability to change the default web browser

### ISSUE THREAD

**Issue by bgatellier** [easyphp/easyphp-devserver#28]
Hi,

I was just wondering if the dev server could suggest to change the web browser used when clicking on the _Open dashboard_ entry of the systray menu.
I use a different browser for web development than the default one.
With the previous version however, it was possible to access the dashboard directly from the URL, so I had a workaround. But in this version, I cannot access the dashboard URL without a first click on this menu entry (which leads to open my default browser).

Hope I was clear enough :)

**Comment by easyphp** [comment]
Yes, cristal clear ;-)
We cannot link the dashboard to a browser. But, for the next version, we can add a simple start button. And then you will be able to use the browser you like.

**Comment by easyphp** [comment]
Hi again
If you don't want to wait for the next version, use the attached file. Unzip, copy "eds-launcher.ini" to "eds-dashboard", replace the old one, stop Devserver and start it again. You will see a new option : "Run Dashboard". Select "Run Dashboard" and open "http://127.0.0.1:1111" with the browser you want to use.
[eds-launcher.zip](https://github.com/easyphp/easyphp-devserver/files/101812/eds-launcher.zip)

**Comment by bgatellier** [comment]
Thanks for this quick improvement. It makes my workflow easier :)

**Comment by StaggerLeee** [comment]
I checked a bit eds-launcher.ini.

Why OpenDashboard link use this: Action: run; FileName: "eds-app-stop.exe"; Parameters: " eds-httpserver"; ShowCmd: hidden ??!!!

There is no logic. Specially when same link cannot start server services.

Now starting servers compared to old version is burried behind many clicks.
Remove this nonsese to stop servers when clicking OpenDashboard, why, why, why !!!????
Use it to open Dashboard with servers active,

And rename and use RunDashboard to start all servers and shutdown them nicely by clicking on this link.

I know there are several servers versions and link maybe cannot know what to chose. Old version remembered what we chosed and started those server versions,

All this is now complicated without any reason.

**Comment by easyphp** [comment]
Ok, we got it. Wait for the next version.

**Comment by StaggerLeee** [comment]
Thank you.
If you can make "localhost" index listing inside Dashboard you are ahead away from Wamp, Xammp, etc... It was inside in old version ? I mean without making virtual hosts, not all people use them.

Or give us some easy template override option (custom folder with template files) for whole Dashboard. You dont have to do everything, we can do some work too. Just to make it easy, and outside updates so it wont be deleted when we update easyphp.

Sorry for offtopic.
