### ISSUE TITLE
Remember last PHP and Port use for APACHE

### ISSUE THREAD

**Issue by CyrilCharlier** [easyphp/easyphp-devserver#29]
Is it possible to remember the last PHP and Port use for APACHE when we stop it ?

![2016-01-23_08h20_05](https://cloud.githubusercontent.com/assets/11455745/12529014/5a960c8c-c1aa-11e5-9451-83ee8990c5b0.png)
![2016-01-23_08h20_15](https://cloud.githubusercontent.com/assets/11455745/12529015/5c700710-c1aa-11e5-9d4b-ae6e77ad1e6a.png)

**Comment by easyphp** [comment]
Thanks for your suggestion.
We will add this feature to the next version.
