### ISSUE TITLE
Devserver 16.1 x64 (VC14) requesting MSVCR110.dll

### ISSUE THREAD

**Issue by Zaarek** [easyphp/easyphp-devserver#32]
Hello, 

Whenever I try to launch the dashboard of EasyPHP Devserver 16.1, I get a system error. It says the program cannot find MSVCR110.dll, although I just installed Microsoft Visual C++ Redistributable for Visual Studio 2015 x64.

Is this a bug or is there an issue on my side?

Thanks!
Zaarek

**Comment by easyphp** [comment]
Hi
See the solution there : http://www.easyphp.org/support.php

**Comment by Zaarek** [comment]
Hi. Thanks for the reply.

I already visited the link you provided. It says: "The VC14 builds require to have the Visual C++ Redistributable for Visual Studio 2015 x86 or x64 installed". 

According to your documentation, the Devserver 16.1 is a VC14 build, so it needs "the Visual C++ Redistributable for Visual Studio 2015 x86 or x64 installed". Which is the case on my PC. I uninstalled all previous VC redists and this one and reinstalled VS 2015 x64 along with EasyPHP 16.1 but It keeps asking for MSVCR110.dll.

Thanks for your help.
Zaarek

**Comment by JohnWilliamB** [comment]
I've had the same issue with the same EasyPHP 16.1 version. I'm on Windows 7x64 pro, and despite trying the MS VC++ 2015 (as linked) my EasyPHP wouldn't work. The dashboard wouldn't start, so I uninstalled the lot, then installed the VC++RT Redist *2012* version (x86), and so far things are working. I hope this helps others.

**Comment by easyphp** [comment]
Thanks for your feedback

**Comment by echo200** [comment]
I have the same issue with EasyPHP 16.1. I'm on Windows 10 x64 pro, and I verified if MSVCR110.dll is already installed  on m'y computer. It is... I uninstalled all previous version of Microsoft Visual C++ Redistributable for Visual Studio x86 or x64. And nothing changed... I don't know what to do more.

**Comment by Lap1Blanc** [comment]
I had the same pb, fixed also by installing 2012 version (x86).

**Comment by akehsanz** [comment]
I'm on Windows 7 x64(64bit) Ultimate. I'd the same problem, so instead of wasting my time uninstalling all MS Redistributables, I just installed VC++RT Redist 2012 version (x86). this solved my problem instantly.

**Comment by Tarqez** [comment]
I can confirm the same on Win10 (upgrade from 8). I installed both x86 and x64 2012 version and this solved the problem.

**Comment by abdelouahabb** [comment]
confirmed here too, I had a headache explaining the difference between Deserver and Webserver but at the end, this DLL broke everything

**Comment by abdelouahabb** [comment]
@easyphp does the PR got resolved ?

**Comment by easyphp** [comment]
@abdelouahabb PR?

**Comment by abdelouahabb** [comment]
Never tried something in the installer :(

**Comment by easyphp** [comment]
Sorry but I don't get it. What do you mean ?

**Comment by abdelouahabb** [comment]
I thought you asked for a PR, and since I have never made an installer, I cant help in this :(

**Comment by lorestomilan** [comment]
mine is EasyPHP Devserver 17 what im using windows 8 and i cant open the dashboard
