### ISSUE TITLE
DevServer 16.1 and Wordpress "Transport http" problems

### ISSUE THREAD

**Issue by funkman733** [easyphp/easyphp-devserver#38]
Hi, I use DevServer 16.1 in Windows 10 pro 64bit OS.
I use it to work in localhost my WordPress sites.
Now I have some problems to update plugins and WordPress system.
When I try to update the system return me this message:
"There are no HTTP transports available which can complete the requested request."
I have searched in google to find a solution but nothing I don't found any worked solutions.
Can you help me, please?

**Comment by StaggerLeee** [comment]
You have to uncomment curl dll in PHP conf file. This module is not activated, despite it should be.
And then on some other place I needed to manually enter path to some file, dont remember now anymore.

Good luck with it, lost several hours fixing it.

**Comment by funkman733** [comment]
Hi, I have uncommented curl dll in PHP conf file but it not work too...

**Comment by StaggerLeee** [comment]
Comment again your curl dll line, and replace with this one. Adapt path to your own settings.

extension=D:/EasyPHP/eds-binaries/php/php5617x160126204528/ext/php_curl.dll

**Comment by funkman733** [comment]
I have do that, but now wordpress don't appear and I have this message:

> L'installazione PHP non ha l'estensione MySQL che è necessaria per utilizzare WordPress.

**Comment by StaggerLeee** [comment]
What happens if you restore line back ?

**Comment by funkman733** [comment]
WordPress return to function but The HTTP Transports are not available..

**Comment by StaggerLeee** [comment]
Be careful with what PHP vesion conf you are editing and pointing to. If you use multiple PHP versions. On my conf it works like this in my example. 

But I had copies many dll files in windows directoris, here and there. Difficult to remember now what helped.  Registered paths in Win 10, etc..

Maybe they should take a look at it. WordPress is most used CMS and if it doesnt work on default they just scare Users to other Wamp applications.

**Comment by StaggerLeee** [comment]
Here are my lines from php.ini, if it can help you somehow:

; Windows Extensions
; Note that ODBC support is built in, so no dll is needed for it.
; Note that many DLL files are located in the extensions/ (PHP 4) ext/ (PHP 5)
; extension folders as well as the separate PECL DLL download (PHP 5).
; Be sure to appropriately set the extension_dir directive.
;
;zend_extension = "D:\EasyPHP\eds-binaries\php\php5617x160126204528\php_xdebug-2.3.3-5.6-vc11.dll"
;xdebug.default_enable=0
;xdebug.remote_enable=0
;xdebug.remote_host=127.0.0.1
;xdebug.remote_port=9000
;xdebug.remote_handler=dbgp
;xdebug.remote_mode=req
;xdebug.remote_autostart = false
;xdebug.dump_globals=1
;xdebug.dump=COOKIE,FILES,GET,POST,REQUEST,SERVER,SESSION
;xdebug.dump.SERVER=REMOTE_ADDR,REQUEST_METHOD,REQUEST_URI
;xdebug.show_local_vars=1
;xdebug.show_mem_delta=1
;xdebug.collect_includes=1
;xdebug.collect_vars=1
;xdebug.collect_params=4
;xdebug.collect_return=1
;xdebug.auto_trace=0
;xdebug.trace_options=0
;xdebug.trace_format=0
;xdebug.trace_output_dir="D:\EasyPHP\eds-binaries\xdebug\trace"
;xdebug.trace_output_name="trace.%t"
;xdebug.profiler_enable=0
;xdebug.profiler_append=1
;xdebug.profiler_enable_trigger=0
;xdebug.profiler_output_dir="D:\EasyPHP\eds-binaries\xdebug\profiler"
;xdebug.profiler_output_name="cachegrind.out.%s.%t"
;extension=php_bz2.dll
extension=D:/EasyPHP/eds-binaries/php/php5617x160126204528/ext/php_curl.dll
;extension=php_fileinfo.dll
extension=php_gd2.dll
;extension=php_gettext.dll
;extension=php_gmp.dll
;extension=php_intl.dll
;extension=php_imap.dll
;extension=php_interbase.dll
;extension=php_ldap.dll
extension=php_mbstring.dll
;extension=php_exif.dll      ; Must be after mbstring as it depends on it
;extension=php_mysql.dll
extension=php_mysqli.dll
;extension=php_oci8_12c.dll  ; Use with Oracle Database 12c Instant Client
extension=php_openssl.dll
;extension=php_pdo_firebird.dll
;extension=php_pdo_mysql.dll
;extension=php_pdo_oci.dll
;extension=php_pdo_odbc.dll
;extension=php_pdo_pgsql.dll
;extension=php_pdo_sqlite.dll
;extension=php_pgsql.dll
;extension=php_shmop.dll

; The MIBS data available in the PHP distribution must be installed. 
; See http://www.php.net/manual/en/snmp.installation.php 
;extension=php_snmp.dll

;extension=php_soap.dll
extension=php_sockets.dll
;extension=php_sqlite3.dll
;extension=php_sybase_ct.dll
;extension=php_tidy.dll
;extension=php_xmlrpc.dll
;extension=php_xsl.dll

**Comment by funkman733** [comment]
Here the mine, and it should be different from yours:
`; Windows Extensions
; Note that ODBC support is built in, so no dll is needed for it.
; Note that many DLL files are located in the extensions/ (PHP 4) ext/ (PHP 5)
; extension folders as well as the separate PECL DLL download (PHP 5).
; Be sure to appropriately set the extension_dir directive.

zend_extension = "C:\Program Files (x86)\EasyPHP\eds-binaries\php\php5617x160113233123\php_xdebug-2.3.3-5.6-vc11.dll"
xdebug.default_enable=0
xdebug.remote_enable=1
xdebug.remote_host=127.0.0.1
xdebug.remote_port=9009
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_autostart = false
xdebug.dump_globals=1
xdebug.dump=COOKIE,FILES,GET,POST,REQUEST,SERVER,SESSION
xdebug.dump.SERVER=REMOTE_ADDR,REQUEST_METHOD,REQUEST_URI
xdebug.show_local_vars=1
xdebug.show_mem_delta=1
xdebug.collect_includes=1
xdebug.collect_vars=1
xdebug.collect_params=4
xdebug.collect_return=1
xdebug.auto_trace=0
xdebug.trace_options=0
xdebug.trace_format=0
xdebug.trace_output_dir=""
xdebug.trace_output_name="trace.%t"
xdebug.profiler_enable=0
xdebug.profiler_append=1
xdebug.profiler_enable_trigger=1
xdebug.profiler_output_dir=""
xdebug.profiler_output_name="cachegrind.out.%s.%t"

extension=php_bz2.dll
;extension=php_curl.dll
extension=C:/Program Files (x86)/EasyPHP/eds-binaries/php/php5617x160113233123/ext/php_curl.dll
;extension=php_fileinfo.dll
extension=php_gd2.dll
;extension=php_gettext.dll
;extension=php_gmp.dll
;extension=php_intl.dll
;extension=php_imap.dll
;extension=php_interbase.dll
;extension=php_ldap.dll
extension=php_mbstring.dll
;extension=php_exif.dll      ; Must be after mbstring as it depends on it
extension=php_mysql.dll
extension=php_mysqli.dll
;extension=php_oci8_12c.dll  ; Use with Oracle Database 12c Instant Client
;extension=php_openssl.dll
;extension=php_pdo_firebird.dll
extension=php_pdo_mysql.dll
;extension=php_pdo_oci.dll
;extension=php_pdo_odbc.dll
;extension=php_pdo_pgsql.dll
extension=php_pdo_sqlite.dll
;extension=php_pgsql.dll
;extension=php_shmop.dll

; The MIBS data available in the PHP distribution must be installed. 
; See http://www.php.net/manual/en/snmp.installation.php 
;extension=php_snmp.dll

;extension=php_soap.dll
extension=php_sockets.dll
extension=php_sqlite3.dll
;extension=php_sybase_ct.dll
;extension=php_tidy.dll
;extension=php_xmlrpc.dll
extension=php_xsl.dll`

**Comment by StaggerLeee** [comment]
You experimented to much. Dont activate both mysql.dll and mysqli.dll.

**Comment by funkman733** [comment]
Ok, I'll deactivate mysqli.dll, but this is the EasyPHP 16.1 DevServer default php.ini....

**Comment by StaggerLeee** [comment]
I dont think it is default code.

**Comment by funkman733** [comment]
I have deactivate mysqli.dll, but I have this message: 

> L'installazione PHP non ha l'estensione MySQL che è necessaria per utilizzare WordPres

**Comment by StaggerLeee** [comment]
Activate this dll and it should work without path: extension=php_openssl.dll

**Comment by funkman733** [comment]
Oh, good!!! Now it work!!!! :D
--


*/GiaNet /Media di Giannetta Francesco*
Via Can. M. Schito, 13
73028 Otranto (LE)
Sito: gianetmedia.com <http://gianetmedia.com>
Mail: gianetmedia@gmail.com <mailto:gianetmedia@gmail.com>
Pec: alterheads@pec.it <mailto:alterheads@pec.it>
Tel: 0836.804422 – 328.3635007 – 333.4651566
C.F.: GNNFNC81C09G751T
P.IVA: 04410590758
Il 17/02/2016 15:34, StaggerLeee ha scritto:

**Comment by Meh0** [comment]
Had the same problem. Activating cURL wasn't enough. With OpenSSL activated too it works now. Didn't need the absolute path to cURL like you did though.
Thank you !
And for other people going through the same trouble : don't forget to restart Easyphp to relaoad the conf of course =)

**Comment by bgatellier** [comment]
FYI, if you set the `extension_dir` PHP directive from _php.ini_, there is no need to specify the absolute path for each extension.

Example:
```
; Directory in which the loadable extensions (modules) reside.
; http://php.net/extension-dir
; extension_dir = "./"
; On windows:
extension_dir = "D:\Dev\EasyPHP-Devserver-16.1\eds-binaries\php\_tests7012\ext"

 Windows Extensions
; Note that ODBC support is built in, so no dll is needed for it.
; Note that many DLL files are located in the extensions/ (PHP 4) ext/ (PHP 5+)
; extension folders as well as the separate PECL DLL download (PHP 5+).
; Be sure to appropriately set the extension_dir directive.

zend_extension=php_opcache.dll
extension=php_curl.dll
extension=php_fileinfo.dll
extension=php_openssl.dll
```

**Comment by easyphp** [comment]
A new version of Xdebug Manager is in development. Which configuration do you use ? You can join the discussion : https://github.com/easyphp/DEVSERVER/discussions and tell us what you need. @bgatellier @StaggerLeee @funkman733 @Meh0
