### ISSUE TITLE
I can't load ZendDebugger extension. - Easyphp devserver 16.1

### ISSUE THREAD

**Issue by gtame** [easyphp/easyphp-devserver#39]
I can't use ZendDebugger with EasyPhp installation. 

1 - I download the ZendDebugger.dll version for php 5.6.
2-  Write settings in php.ini file.

`[Zend Debugger]
zend_extension="E:\ZendDebugger.dll"
zend_debugger.allow_hosts=127.0.0.1,192.168.0.1/255
zend_debugger.expose_remotely=always
zend_debugger.httpd_uid=-1`

3- When I start server, zend_extension setting is override automatically with php_xdebug-2.3.3-5.6-vc11.dll location.

**Comment by easyphp** [comment]
You can edit the file "eds-app-settings.php" in your PHP directory.

**Comment by easyphp** [comment]
A new version of Xdebug Manager is in development. Which configuration do you use ? You can join the discussion : https://github.com/easyphp/DEVSERVER/discussions and tell us what you need. @gtame
