### ISSUE TITLE
Virtual host manager - Dashboard

### ISSUE THREAD

**Issue by mackovikm** [easyphp/easyphp-devserver#40]
After instal Virtual Manager 1.6 on Dev Server 16.1 RC5 has this error on Dashboard 

`Warning: file_get_contents(store_vhosts_off.php): failed to open stream: No such file or directory in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-modules\virtualhostsmanager\virtualhostsmanager.php on line 87

Warning: array_merge(): Argument #2 is not an array in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-modules\virtualhostsmanager\virtualhostsmanager.php on line 88`

**Comment by easyphp** [comment]
It seems to be a little bug. We will fix it today and publish a new version.

**Comment by easyphp** [comment]
Fixed!
You can download Virtual Hosts Manager 1.6.1.
http://warehouse.easyphp.org
