### ISSUE TITLE
Error SQL phpmyadmin while importing SQL file to fill new database

### ISSUE THREAD

**Issue by Trebly** [easyphp/easyphp-devserver#41]
Hi,
I get the error

> Erreur
> 
> Requête SQL : DocumentationModifier Modifier
> 
> SELECT `comment`
>                FROM `phpmyadmin`.`pma__column_info`
>               WHERE db_name     = 'blg1-1a'
>                 AND table_name  = ''
>                 AND column_name = '(db_comment)'
> 
> MySQL a répondu: Documentation
> # 1100 - Table 'pma__column_info' was not locked with LOCK TABLES

I had just before 
- installed devserver 16.1
- fixed as asked (button) the tables of phpmyadmin (advanced options not set)
- create an empty database ("blg1-1a")
- launch import without option from an dump coming from 5.5.46 mysql (current version run by OVH)

This seems a phpmyadmin script problem.
For now devserver is not usable.

Best regards

Trebly

**Comment by easyphp** [comment]
Hi. This not a Devserver bug. Please, check PhpMyAdmin website.
