### ISSUE TITLE
16.1 Error connecting to database with PhpStorm

### ISSUE THREAD

**Issue by Icety** [easyphp/easyphp-devserver#43]
I have installed the new 16.1 devserver with Mysql 5.7.11, and the newest phpMyAdmin. 
My sites run fine, but when I try to connect to the database through PhpStorm I get the following error:
Connection to MySQL - mydatabase@localhost failed
Table 'performance_schema.session_variables' doesn't exist.

I have looked it up and it tells me to upgrade mysql throught the command prompt, yet when I try this I get another error:
mysql_upgrade: [Error] 1146: Table 'mysql.innodb_table_stats' doesn't exist.

**Comment by Icety** [comment]
I appeared to have forgotten the --force command:
mysql_upgrade -u root -p --force
This command fixes it, yet maybe it would be wise to fix the mysql to work immediately.

**Comment by marctonon** [comment]
I had exactly the same issue, but the command didn't fix it. Now, the problem is another: performance_schema_table in wrong format.

Why we have to use this command? Was not supposed to be ready for use after install?

**Comment by Icety** [comment]
Did you restart the mysql? That fixed it for me.

**Comment by Otienoh** [comment]
This is caused by compatibility issues btw the two versions of mysql i believe, to resolve try using the below comands 
```
mysql -u app -p
mysql> set @@global.show_compatibility_56=ON;
```
this fixed it for my phpstorm and workbench issues.

**Comment by luckylast** [comment]
if you still see this error "Table 'performance_schema.session_variables' doesn't exist." after try above solution, check out below article, you need to follow these steps
http://epagetech.com/blog/fatal-error-maximum-execution-time-of-30-seconds-exceeded-after-change-php-ini-file-still-show-this/
