### ISSUE TITLE
[Feature Request] PHP 64-bit builds for Devserver 16.1

### ISSUE THREAD

**Issue by loostro** [easyphp/easyphp-devserver#44]
32-bit builds of PHP:
* Integers can be from -2,147,483,648 to 2,147,483,647 (~ ± 2 billion)

64-bit builds of PHP:
* Integers can be from -9,223,372,036,854,775,808 to 9,223,372,036,854,775,807 (~ ± 9 quintillion)

Please provide 64-bit builds of PHP (especially php7 and php 5.6) for Devserver 16.1.

**Comment by easyphp** [comment]
Noted. We will publish 64-bit builds.

**Comment by loostro** [comment]
Thanks.

**Comment by PatriceDargenton** [comment]
EasyPHP-Devserver-16.1.1-setup.exe installs MySql in 32 bits although there is a 64 bits of MySql : a 64 bit version of EasyPHP is still planned ? Thanks.
