### ISSUE TITLE
Opening dashboard from try icon force stops the services

### ISSUE THREAD

**Issue by SublymeRick** [easyphp/easyphp-devserver#45]
When I dont have a dashboard open and I need to load phpmyadmin I'll right click the tray icon and click open dashboard the dashboard loads up and indicates the services are stopped (by the green start buttons) when the services were running immediately prior to launching the dashboard.

This happens on my laptop which I do hibernate between work sessions so this may be a bug caused by loading the dashboard after a restore from hibernation. I have not done more testing to see if thats the issue but I have a feeling it might be.

Windows 10 64
Devserver 16.1

**Comment by easyphp** [comment]
This behavior will be changed with the next version.
Meanwhile, see #28.
