### ISSUE TITLE
Kaspersky Antivirus & EasyPHP Dashboard

### ISSUE THREAD

**Issue by StaggerLeee** [easyphp/easyphp-devserver#46]
Latest versions of Kaspersky Home products have some new technology to help protect people when surfing web. But it seems it prevents Dashboard to open, and in the same time of course starting both servers. If you disable this option in Settings - Additional - Network - Inject script into web traffic to interact with web pages Dashboard opens. Later you can activate this option again, Apache and PHP servers dont have problem with it, just Dashboard will not open. I mean you can work developing websites normally. 

Lost whole one day on this stupid thing, and will write it here if it can save time for some of you. And to the developers to check if they can slightly change something inside Dashboard template to make it work with latest Kaspersky . It is after all one of the most used Antivirus software.

[http://forum.kaspersky.com/index.php?showtopic=316466](url)

> Kaspersky Lab would like to explain the injection of special script in web pages loaded in users’ browsers. This technology is going to replace the obsolete plugin technology in our consumer products launched or updated in 2015 and later on. The new protection technology adds a special script to a web page shown to the user, which does not send any data from the computer to third-party servers but works as a communication channel between the browser and our security solution. This interaction is performed in the form of sending requests to a special technical URL, which the browser interprets as addressing a remote server, however, instead of the remote server these special requests are handled by security solution, running locally. This means that no information leaves the computer via this script.
> This technology is used by several components of Kaspersky Lab solutions for home users, including web antivirus, anti-phishing and Safe Money. As this technology was designed solely for the purpose of providing better protection, our products currently do not offer an option of disabling this script. However, our experts are currently working on modifications to the company’s solutions that will enable users to disable the script if they desire. This change may be included in forthcoming updates.

**Comment by easyphp** [comment]
Thanks for your message.
We are going to check this. It's on our todo list...
