### ISSUE TITLE
trojan horse in devserver 16.1

### ISSUE THREAD

**Issue by mjt78** [easyphp/easyphp-devserver#50]
hi,
i would like to install easyphp devsever 16.1, and it was put in quarantine by mcafee.
Artemis!C420FC0458D0 was detected.
have you an other version without trojan?
thanks for your help

**Comment by easyphp** [comment]
No worries. There is no troyan or virus. Your antivirus is too sensitive. You can stop it for a few minutes, and then install EasyPHP Devserver.

**Comment by cmalard** [comment]
Hi there,

Same issue with McAfee on Win10.
Maybe you should work with them to fix that, this is really creepy.

**Comment by zerotyler** [comment]
Hi there,

Same issue with McAfee and Win8 and Win10
