### ISSUE TITLE
[Feature Request] Include mysqld.exe tool in MySQL binaries for Devserver 16.1

### ISSUE THREAD

**Issue by loostro** [easyphp/easyphp-devserver#62]
Please include `mysqld.exe` tool in MySQL binaries for Devserver 16.1

**Comment by easyphp** [comment]
It is. You just need to copy and paste eds-dbserver.exe and rename it.

**Comment by loostro** [comment]
Thanks for info. Maybe you should add `mysqld-README.txt` with this info? Anyone looking for this binary (in the `bin` folder) will see this text file.
