### ISSUE TITLE
After Installation php 7.0.5 don't see it

### ISSUE THREAD

**Issue by CyrilCharlier** [easyphp/easyphp-devserver#63]
Hello,

after installing PHP 7.0.5 x64 i don't see it in WebSite Admin

![2016-04-15_10h18_10](https://cloud.githubusercontent.com/assets/11455745/14555548/86446bdc-02f3-11e6-99fb-a0e00f94a154.png)

**Comment by CyrilCharlier** [comment]
Even after a complete restart

**Comment by easyphp** [comment]
Normal. PHP x64 cannot work with Apache x86. You need Apache x64.

**Comment by CyrilCharlier** [comment]
oh.. just forgot this ! 

Will try, thanks

**Comment by CyrilCharlier** [comment]
Ok that work
