### ISSUE TITLE
PHP Admin

### ISSUE THREAD

**Issue by kensoftSolutions** [easyphp/easyphp-devserver#64]
I have found the much better than xamp.
I have used xampp for over a year now.

Some features of Php admin are disabled..

How can this be solved?

If this is sorted then easyphp-devserver is the best.

Regards

Azhar

**Comment by CyrilCharlier** [comment]
Hi,

What functionality you talking about?

thanks,

**Comment by DigitalMarketingK** [comment]
Dear Cyril,
Attached find the error in 1.png anf 2.png. File 3.png shows my configuration.
Any help given will be highly appreciated.
Regards

I post with a diiferent account as i am unable to log inot my previous account.
(Have writtenn to GitHub Support about this)
![1](https://cloud.githubusercontent.com/assets/18571261/14669552/dec1ff82-0702-11e6-9fb0-397ce50759c5.png)
![2](https://cloud.githubusercontent.com/assets/18571261/14669553/deeb175a-0702-11e6-84ca-d1704c4f139c.png)
![3](https://cloud.githubusercontent.com/assets/18571261/14669554/df8a7cc8-0702-11e6-8dc6-d296ce5f42fb.png)

**Comment by DigitalMarketingK** [comment]
You can see the red marked lines

**Comment by CyrilCharlier** [comment]
I got the same error. Will try to activate it and i will post back here

**Comment by CyrilCharlier** [comment]
You can see here : 
http://docs.phpmyadmin.net/fr/latest/config.html  (in french) to see how to configure these options

**Comment by kensoftSolutions** [comment]
Thank you,

See when i install xampp , the phpadmin has some default tables which were
missing in EasyPHP Server.

Try to request the technical team to activate the features from the point
go.

For now will stick to Xampp. Although your product was much better in all
other aspects.

Regards

Azhar

**Comment by CyrilCharlier** [comment]
it is not my product ;) i try only to answer

**Comment by DigitalMarketingK** [comment]
ok thanks for you help.

You have been very helpfull


Hope the people who matter , read this.

**Comment by DigitalMarketingK** [comment]
The default tables from xampp
![4](https://cloud.githubusercontent.com/assets/18571261/14671121/96107168-0709-11e6-9f28-da8f64c25546.png)

**Comment by DigitalMarketingK** [comment]
There is no user db at the ,moment

**Comment by CyrilCharlier** [comment]
i see, in phpmyadmin, all these database are hidden in the phpmyadmin config : 

$cfg['Servers'][$i]['hide_db'] = '(mysql|information_schema|performance_schema|test|phpmyadmin)';
