### ISSUE TITLE
Unable to load php_intl extension in EasyPHP Deveserver 16.1.1 on Windows 10-32bit

### ISSUE THREAD

**Issue by shashankitsoft** [easyphp/easyphp-devserver#66]
I have installed EasyPHP 16.1.1 on Windows 10 Pro- 32 bit: Apache 2.4.18, PHP 7.0.4, MySQL 5.7.11.

Wanted to install Magento 2.0.4. So, I have enabled all extensions required for it https://blog.amasty.com/how-to-install-magento-2-php7-localhost/ When I checked phpinfo,**all other required extensions are loaded, except php_intl.dll**. Checked apache error log: 
`PHP Warning: PHP Startup: Unable to load dynamic library 'E:\\easyphp\\eds-binaries\\php\\php704vc14x86x160503020456\\ext\\php_intl.dll' - The specified module could not be found.\r\n in Unknown on line 0`

I checked, file php_intl.dll is available there in ext folder in php directory. Still it not loading. Why? What to do?

And what is meant by (Refer to #25 )

> Copy the icu*.dll files from the php directory to the apache/bin directory

? Where/which are these files?
Let me know the solution to load intl.

Also please tell me how to install and enable imagick in easyphp devserver.

Thanks.

**Comment by bgatellier** [comment]
Issue can now be closed (answer in #25).

**Comment by F4LK0N** [comment]
I have the definitive solution!!!

Add the path of the PHP folder to the Windows System Paths Variable 
(Right click on 'My Computer' > 'Properties' > 'Advanced System Settings' > 'Environment Variables')

Restart the computer.
