### ISSUE TITLE
xdebug not loaded in DevServer 16.1.1 Apache 2.4.20 x86 - PHP 5.6.21 x86

### ISSUE THREAD

**Issue by GeorgeBotsev** [easyphp/easyphp-devserver#67]
Hello,
I am not quite sure how this should be in general, but I just tested and in my tests, unless I specify 
`zend_extension = "php_xdebug-2.4.0-5.6-vc11.dll"` in php.ini, then the xdebug is not loaded for me, and I cannot make a breakpoint :)
I have by default the line for zend_extension - blank and commented out.

**Comment by bgatellier** [comment]
Hi,

[That's the good way to handle this extension](https://xdebug.org/docs/install) ;-)

**Comment by easyphp** [comment]
A new version of Xdebug Manager is in development. Which configuration do you use ? You can join the discussion : https://github.com/easyphp/DEVSERVER/discussions and tell us what you need. @bgatellier @GeorgeBotsev
