### ISSUE TITLE
[16.1] [Apache 2.4.20 VC14 x86] [PHP 7.0.6 VC14 x86] Apache crash and do not launch

### ISSUE THREAD

**Issue by bgatellier** [easyphp/easyphp-devserver#68]
Hi,

I installed the last Apache and PHP version at that time, and when I try to start PHP the following error occurs in a Window-style popup (sry for the french text, but I'm afraid that my english translation will not be very accurate in that case) :

> Le point d'entrée de procédure php_network_gethostbyname est introuvable dans la bibliothèque de liens dynamiques C:\......\eds-binaries\php.........\ext\php_sockets.dll.

The english translation would be something like:

> The procedure entry point php_network_gethostbyname could not be located in the dynamic link library C:\......\eds-binaries\php.........\ext\php_sockets.dll.

**Comment by urosevic** [comment]
I wish to confirm that same issue experienced with PHP php707vc14x86x160604120652 on Apache 2.4.20 x86:

> The procedure entry point php_network_gethostbyname could not be located in the dynamic link library C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-binaries\php\php707vc14x86x160604120652\ext\php_sockets.dll

Error does not appear with php704vc14x86x160604114913

**Comment by openmagecz** [comment]
Have the same issue for lot of modules in PHP 7.1 RC 1 and PHP 7.1 RC2. For example these modules are blocking Apache to start:

php_mbstring.dll, php_mysqli.dll, php_openssl.dll, php_pdo_mysql.dll, php_pgsql.dll, php_soap.dll, php_sockets.dll, php_xmlrpc.dll

**Comment by REJack** [comment]
> The procedure entry point php_network_gethostbyname could not be located in the dynamic link library C:\......\eds-binaries\php.........\ext\php_sockets.dll.

I had similar errors but with the `php_pdo_pgsql.dll`,
my PHP 5.6 catched the modules from PHP 5.5, check your error log if you get errors like: 
```
PHP Warning:  PHP Startup: curl: Unable to initialize module\nModule compiled with module API=20131226\nPHP    compiled with module API=20121212\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: gd: Unable to initialize module\nModule compiled with module API=20131226\nPHP    compiled with module API=20121212\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: mbstring: Unable to initialize module\nModule compiled with module API=20131226\nPHP    compiled with module API=20121212\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: mysql: Unable to initialize module\nModule compiled with module API=20131226\nPHP    compiled with module API=20121212\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: mysqli: Unable to initialize module\nModule compiled with module API=20131226\nPHP    compiled with module API=20121212\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: openssl: Unable to initialize module\nModule compiled with module API=20131226\nPHP    compiled with module API=20121212\nThese options need to match\n in Unknown on line 0
```

I had this error only because I'm added the PHP 5.5 path to the system environment variable `PATH` and now i use PHP 5.6.

**Comment by openmagecz** [comment]
For me installing vc_redist.x64.exe was a solution. So maybe some of you can only check if you have really Visual C++ Redistributable for Visual Studio installed.

**Comment by REJack** [comment]
That's a system requirement :smile: any easyPHP user should have this installed.

> Visual C++ Redistributable for Visual Studio 2015 x86 or x64 required
