### ISSUE TITLE
EasyPHP registration 

### ISSUE THREAD

**Issue by slicingabebe** [easyphp/easyphp-devserver#70]
Please, where  find "REGISTRATION" button to open WAREHOUSE then?

**Comment by mommundsonBP** [comment]
Pretty sure you need to pay. The fact that you need to pay to access the modules isn't very forthcoming on any of their webpages though.
![image](https://cloud.githubusercontent.com/assets/19790637/15845825/1b3c44b8-2cba-11e6-9b75-8e291c114149.png)

**Comment by CyrilCharlier** [comment]
Yes you need to donate to access warehouse.

**Comment by mommundsonBP** [comment]
Thanks for confirming. :)

**Comment by CyrilCharlier** [comment]
i have donate, so i know that ;)

**Comment by mommundsonBP** [comment]
Donated. I wanted access to the MediaWiki module.....which is no longer available! oi vay! *sigh*

**Comment by CyrilCharlier** [comment]
It is easy to install it, no need a module for that. Where do you block when you manually install it ?

**Comment by mommundsonBP** [comment]
Its just time consuming and i only wanted to demo it so i could convince a manager at work that its the best collaboration and knowledge repository, if you want technician engagement. Admittedly, i could have just manually installed it with how much time i have spent on this *ooops* I will give it a go and report back if i have any issues. Thanks :+1:

**Comment by mastacheata** [comment]
I'm pretty sure they'll / he'll add that stuff again.
It's also strange that the warehouse lists all kind of stuff, but if you want ruby and python you have to grab it from the front page.
