### ISSUE TITLE
Win32/HideExec.NAA

### ISSUE THREAD

**Issue by mdverhoeven** [easyphp/easyphp-devserver#72]
Looks like an awesome product but having it flagged by ESET as having Win32/HideExec.NAA embedded does not fill me with confidence.

I am not too fond of "switching off for a few minutes" so was hoping to see this issue resolved in another way. Any ideas about that?

**Comment by mastacheata** [comment]
If you read a little more, you'll notice that most AV systems categorize this as Risk/Riskware/not-a-virus.
(See: https://www.virustotal.com/en/file/11a1accb700291e7d119217651310b3af7d3d9c97103c66fb432076dcacc0080/analysis/ )
Basically that means the EasyPHP installer is using a technique common to adware and viruses for whatever reason.
That technique by itself is not a bad thing. That's also why 44 out of 53 virus scanners don't detect it at all.
