### ISSUE TITLE
Unable to run Apache and MySQL at all

### ISSUE THREAD

**Issue by DreadfulCthulhu** [easyphp/easyphp-devserver#73]
It happens without any settings, since fresh installation of Windows 10. EasyPHP can start those services, but don't know, that services are running after they are started.See video
[https://www.youtube.com/watch?v=FhNmIh-80NY](url)

EDIT: URL was wrong
EDIT2: URL not working here, just copy link above

**Comment by DreadfulCthulhu** [comment]
Apache Error log:
`[Tue Jun 14 12:57:58.135769 2016] [core:warn] [pid 1428:tid 592] AH00098: pid file C:/Program Files (x86)/EasyPHP-Devserver-16.1/eds-binaries/httpserver/apache2418vc11x86x160614125725/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
PHP Deprecated:  Comments starting with '#' are deprecated in C:\\Program Files (x86)\\EasyPHP-Devserver-16.1\\eds-binaries\\php\\php5619vc11x86x160614125725\\php.ini on line 877 in Unknown on line 0
[Tue Jun 14 12:57:58.208389 2016] [mpm_winnt:notice] [pid 1428:tid 592] AH00455: Apache/2.4.18 (Win32) PHP/5.6.19 configured -- resuming normal operations
[Tue Jun 14 12:57:58.208889 2016] [mpm_winnt:notice] [pid 1428:tid 592] AH00456: Apache Lounge VC11 Server built: Dec 11 2015 11:26:53
[Tue Jun 14 12:57:58.209898 2016] [core:notice] [pid 1428:tid 592] AH00094: Command line: '..\\eds-binaries\\httpserver\\apache2418vc11x86x160614125725\\bin\\eds-httpserver.exe -d C:/Program Files (x86)/EasyPHP-Devserver-16.1/eds-binaries/httpserver/apache2418vc11x86x160614125725'
[Tue Jun 14 12:57:58.220909 2016] [mpm_winnt:notice] [pid 1428:tid 592] AH00418: Parent: Created child process 9756
PHP Deprecated:  Comments starting with '#' are deprecated in C:\\Program Files (x86)\\EasyPHP-Devserver-16.1\\eds-binaries\\php\\php5619vc11x86x160614125725\\php.ini on line 877 in Unknown on line 0
[Tue Jun 14 12:58:00.976255 2016] [mpm_winnt:notice] [pid 9756:tid 504] AH00354: Child: Starting 64 worker threads.
[Tue Jun 14 13:03:59.595562 2016] [mpm_winnt:crit] [pid 9756:tid 504] AH02538: Child: Parent process exited abruptly. Child process is ending
[Tue Jun 14 13:04:01.627355 2016] [mpm_winnt:notice] [pid 9756:tid 504] AH00364: Child: All worker threads have exited.`

**Comment by bgatellier** [comment]
Hi,

Do you have other applications that could run on port 80 (like Skype) ?

**Comment by DreadfulCthulhu** [comment]
No, there is no problem, when I'm clickin on Start button, there is Port 80, after refresh, there is 8080 after refresh there is I don't remember that numbers now, but maybe 3 next port numbers. Finaly I can run Apache 5 times, each on its own port, but easyphp still don't know at least about one of them.

**Comment by bgatellier** [comment]
Did you try to launch EasyPHP after Windows startup with no other software running at the same time?

**Comment by DreadfulCthulhu** [comment]
I have installed only Netbeans and Opera, but that problem was before Netbeans installation too, so I mean, it was installed on fresh system (after Opera installation) and then started with problems.

**Comment by bgatellier** [comment]
What I mean is that on your video there is a lot of tray icons, and I would like to be sure that there is no other software that could conflict with EasyPHP.

**Comment by SundownDev** [comment]
hey I have the same problem, but only w/ php7, because if you try to start two times with php5 it works. I can start mysql.

When I try to launch php.exe in /php7/ folder, it says "Impossible to launch program because VCRUNTIME140.dll is missing. Try to reinstall the program to fix the problem."

**Comment by SundownDev** [comment]
now it says "api-ms-win-crt-runtime-l1-1-0.dll" is missing :(
Tried [this (http://www.microsoft.com/en-us/download/details.aspx?id=48145)](http://www.microsoft.com/en-us/download/details.aspx?id=48145) but I just can't install it at all..

**Comment by Deltafox79** [comment]
I have the same issue on win 10 x64 , I have installed the latest runtime 14.0.24212 and can't downgrade to 14.0.23026.. any fix? apache start but not work

**Comment by REJack** [comment]
I reinstalled my Win10 x64 few days ago and DevServer 16.1 works flawless, i use a [AIO Runtimes](https://www.sereby.org/site/All%20in%20One%20Runtimes&lang=en)  installer to get all runtimes installed without any failure :smile: 

VCRUNTIME140.dll Version: 14.0.24210.0

**Comment by Marion904** [comment]
Hi DreadfulCthulhu,

I have the same error message : have you solved your problem?
