### ISSUE TITLE
Mysql corrupt connection 

### ISSUE THREAD

**Issue by frvenixx** [easyphp/easyphp-devserver#74]
**Under windows 10**

I change the php config file (max upload file for example)
[version : 5.6.19 compiler : VC11 architecture : x86 (32-bit) xdebug : 2.4.0]
I restart the http server 
And in my browser i get the following message 

> Database error: cannot connect to Database Plugin '*6DDCE99257B40F23A39CE60BB7648C2B34B4A116' is not loaded
> MySQL Error
> Session halted

What's happen... i don't understand..

**Comment by bgatellier** [comment]
Hi,

The error you're giving seems not related to the modifications you've made.
Did you try to undo the php.ini modifications and then restart the Apache server ?

Could you also provide the change you've made to the php.ini file ?

**Comment by frvenixx** [comment]
you are right. I think it happens when I stop and start mysql manually. 
How stop properly easyphp services. manually or with the Exit option.

**Comment by frvenixx** [comment]
**I confirm the issue.** 

I stop easyphp by Exit option (trail icon).
I restart easyphp normally by icon desk and launch Open Dashboard option.
All seem ok. main page appear on browser. but when i launch my website, i get always this message 

> Database error: cannot connect to Database Plugin '*6DDCE99257B40F23A39CE60BB7648C2B34B4A116' is not loaded
> MySQL Error
> Session halted.

any ideas ?

**Comment by bgatellier** [comment]
Do your Apache server starts at the same time as the dashboard ?
Because the server that allows EasyPHP to run the dashboard is not related to the Apache server you have to start to make your website work.

**Comment by frvenixx** [comment]
Yes. open port controller show eds-dashboard / eds-dbserver / eds-httpserver. All work fine.

In phpmyadmin, when I try to change privileges of a user (no grant) i get the same message
When i try to connect mysql database with odbc32 drivers. Same message. 
But with the Root user, connection work ! The issue dissapears in my web browser...

any ideas ?

**Comment by bgatellier** [comment]
Could you please provider the Apache error log and the code you try to execute ?
