### ISSUE TITLE
Home Page Notificatoion bug.

### ISSUE THREAD

**Issue by legndery** [easyphp/easyphp-devserver#75]
Giving 
`"Parse error: syntax error, unexpected 'autoSubmit' (T_STRING), expecting ')' in C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-dashboard\notification.php on line 38"`

on opeining 127.0.0.1:1111.

in notification.php 

line 38: `<body onload='autoSubmit()'>`

`autoSubmit()` is not escaped.

**Comment by bgatellier** [comment]
Hi,

Is it a fresh new installation?
If not, when did this error occured?

**Comment by legndery** [comment]
Fresh Installation. Just installed the new version. and Opened the Dashboard.

**Comment by bgatellier** [comment]
I just installed the latest version (16.1.1), and the file you mention (notification.php) does not contains so much lines (only 1).
Is this bug occurs each time you start EasyPHP?
Could you please provide the content of the `notification.php` you have?

**Comment by legndery** [comment]
I think this is a problem on my side(or for users like me). I login to my ISP through a web interface(cable Internet). you will see what I mean when you see the notification file. but I saw that the notification.php is kinda dynamic I guess it's being parsed from other php file.
By looking at the sources I think from 
```
eds-dashboard/index.php line 153, 160
file_put_contents('notification.php', $new_content);
```
and 
```
eds-dashboard/notification_redirect.php line 10
file_put_contents('notification.php', $new_content);
```
So escaping the string from `eds-dashboard/index.php line 152 $content_array[0]` would do the trick I think.

This is my notification.php (stripped some personal info)
```
<?php $notification = array('check_date'=>'20160618','date'=>'











<html><head>
<meta http-equiv=pragma content=nocache>
<META HTTP-EQUIV=Expires CONTENT=-1>
<script language="Javascript">
    function autoSubmit(){
	//alert("Auto submit from redirection.jsp");
	document.forms[0].submit();
    }
</script>
</head>
<!--
<?xml version="1.0" encoding="UTF-8"?>
<WISPAccessGatewayParam xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.acmewisp.com/WISPAccessGatewayParam.xsd">
<Redirect>
<AccessProcedure>1.0</AccessProcedure>
<AccessLocation>Ahmedabad</AccessLocation>
<LocationName>Ahmedabad</LocationName>
<LoginURL>https://testipass.com/24online/servlet/smartclient?mode=1</LoginURL>
<MessageType>100</MessageType>
<ResponseCode>0</ResponseCode>
</Redirect>
</WISPAccessGatewayParam>
-->


<body onload=\'autoSubmit()\'>

<FORM ACTION="<my_isp_login_url>" METHOD=POST>
<INPUT TYPE=hidden NAME=url VALUE="http://www.easyphp.org:80/notifications/notification-easyphp-devserver.txt">
<INPUT TYPE=hidden NAME=ipaddress VALUE="<my_internal_ip>">
<INPUT TYPE="hidden" NAME="formsubmiturlIP" VALUE="<isp_main_router_ip>">
</FORM>
</body>
</html>

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>
','status'=>'0','link'=>'','message'=>'','link_text'=>''); ?>
```

and note that the html string is mapped to the key  `$notification['date'];`

Sorry for the unnecessarily detailed message.

**Comment by bgatellier** [comment]
You're right, the `notification.php` is generated by the PHP code, after a previous request to an online web site.
So I suppose that you're disconnected from your ISP when you try to display the dashboard.
If you can try to first login to your ISP then launch the dashboard, I think it should work.

**Comment by bgatellier** [comment]
Whatever the solution, this issue is not related to _EasyPHP Dev server_, but to a specific behaviour of web-based ISP authentication.
So I encourage you to report this kind of issue in a more appropriate tool like [Stackoverflow](http://stackoverflow.com/).

**Comment by legndery** [comment]
Yeah ok. But a simple escaping would do the trick even though it is an undefined behaviour. The dashboard would still open instead of showing a syntax error.

**Comment by bgatellier** [comment]
It seems that you already tried, so I guess it will do the trick for your case.

But I think that a better solution would be to test the HTTP response (code 200) when the php code do a request to an external website.
