### ISSUE TITLE
.htaccess: Invalid command 'AddOutputFilterByType', perhaps misspelled or defined by a module not included in the server configuration, referer: http://127.0.0.1:1111/

### ISSUE THREAD

**Issue by venividi2** [easyphp/easyphp-devserver#76]
When I try to lunch a file from Apache, I see this .htaccess lockup I found in the Apache errorlog. What can I do ? Until now the previous easyphp versions (I have now installed the 16.1, returning to one of the old version the problem is the same) worked correctly, but now that I had to overhaul my system (I have windows 10) I am lost. I've already looked around but I can't find a way out.

**Comment by bgatellier** [comment]
Hi,

What did you already try?
And can you provide your .htaccess file?

**Comment by venividi2** [comment]
Hello, Bastien, thank you for answering

I uncommented the following in the Apache httpd.conf file : #LoadModule 
filter_module modules/mod_filter.so

but, it looks worse than before, now the error log says :

[Mon Aug 08 20:51:18.860054 2016] [core:alert] [pid 5572:tid 1112] [client 127.0.0.1:50350] F:/shopshop/berkel-sito/.htaccess: Unknown filter provider DEFLATE, referer: http://127.0.0.1:1111/

Here is the current .htaccess content (I'm working locally):

AddOutputFilterByType DEFLATE text/plain
AddOutputFilterByType DEFLATE text/html
AddOutputFilterByType DEFLATE text/xml
AddOutputFilterByType DEFLATE text/css
AddOutputFilterByType DEFLATE application/xml
AddOutputFilterByType DEFLATE application/xhtml+xml
AddOutputFilterByType DEFLATE application/rss+xml
AddOutputFilterByType DEFLATE application/javascript
AddOutputFilterByType DEFLATE application/x-javascript


Thanks a lot
Valeria
PS I was a webmaster until 10 years ago. I am now trying to build my daughter's site but I've recently turned 74 and it takes me 20 times longer to do things (and to understand them), so please be patient if you can help me


Il 08/08/2016 19:57, Bastien Gatellier ha scritto:

**Comment by bgatellier** [comment]
It seems that [the Apache module `mod_deflate`](https://httpd.apache.org/docs/current/en/mod/mod_deflate.html) is not loaded.
Could you try to locate the following line and see if it's commented?
```
#LoadModule deflate_module modules/mod_deflate.so
```
Then restart Apache.

You're the first person I "know" who has so much experience in web development. It makes me confident for my future ;-) I appreciate your will and efforts to explain your problem and try to solve it.

**Comment by venividi2** [comment]
Thanks. Let me see if it works. Oh yes, yes, yes, it does  ! I now 
understand what to do should there be other problems

Thank you very very very much ! I am so happy now that I can continue. 
I'll build the site locally and load it as a static multilanguage site.

Have a nice day
Valeria


Il 08/08/2016 23:22, Bastien Gatellier ha scritto:
> #LoadModule deflate_module modules/mod_deflate.so

**Comment by bgatellier** [comment]
You're welcome !
