### ISSUE TITLE
Need some extensions

### ISSUE THREAD

**Issue by andreaspada** [easyphp/easyphp-devserver#77]
Hi! I'm currently trying tour devserver - quite charming... - and I need some extensions to properly use my software. I need PHP Curl and PHP OpenSSL.  How can I install that?

Thanks,
Andrea

**Comment by CyrilCharlier** [comment]
Hi,

Go to your php.ini and uncomment it ;)

**Comment by andreaspada** [comment]
Cool! Sorry for such a basic question, but I'm so new to Windows... I used Linux for a dozen years than switched to OSX and everything is so different there. I feel that I have to re-learn almost everything.

Cheers

**Comment by CyrilCharlier** [comment]
No problem ;) ask if you want, i will help you if i can :)

**Comment by CyrilCharlier** [comment]
oh and you can close your issue ;)
