### ISSUE TITLE
[Codiad] Others directories ?

### ISSUE THREAD

**Issue by CyrilCharlier** [easyphp/easyphp-devserver#78]
Hi,

Good addition for Codiad thanks !
How can we open others directories than project ? 

For example : A symfony project is :  
/
/src
/vendor
/web
...

/web is the root directory for apache. 
But how to open / directory ?

thanks

**Comment by REJack** [comment]
Do you mean a "Working Directory"? On the main dashboard of Devserver 16.1 with the new Codiad beta is a "Working Directory"-Section there you can add directories to edit in Codiad.

I hope this helps you :smile:
