### ISSUE TITLE
Allow remote access to VHosts

### ISSUE THREAD

**Issue by mastacheata** [easyphp/easyphp-devserver#79]
It would be great to have a switch somewhere to allow remote access to VHosts created by the Virtual Host Manager Addon.

It's sad that the  code is so densely packed and unmodular. Makes it really hard to see what you did there. 
The serialized store_vhosts.php file doesn't contain the IPs, yet when I restart the server, the virtualhosts file is reset to the automated state without my modifications.

**Comment by lommes** [comment]
I haven't tested this in detail, but when you create a new virtual host, there is a step 4 (expert mode) where you can modify this

If you remove
```
Order deny,allow
Allow from 127.0.0.1
Deny from all
Require all granted
```
everybody should be able to access

**Comment by mastacheata** [comment]
That's only part of the problem.
You allow access from outside, but only if the request is targeted at the local network IP.
That is due to the VirtualHost block definition, which looks roughly like this:
<VirtualHost 127.0.0.1:80> ... </VirtualHost> (I'm not sure whether it's binding to 127.0.0.1 or the LAN IP, but it's definitely not answering when you request from outside the LAN Gateway)

An easy fix would be to replace the explicitly defined IP by an asterisk wildcard.

**Comment by easyphp** [comment]
Devserver is for local development only, so we won't allow access from outside.
If you want to use your server as a web server, you can use EasyPHP Webserver (btw a new version is coming). And you have to configure your firewall (if any) and your router.

**Comment by mastacheata** [comment]
> If you want to use your server as a web server, you can use EasyPHP Webserver
Thanks, but that's not what I wanted to do when I opened this issue.

I really needed an easy to set up dev environment for Windows that I could build and test local area web applications with.
Local area as in Local Area Network, not as in localhost.
The scenario was receiving callbacks/webhook events from devices in my LAN.

Also this is marketed as a DEV Server and by that I expect to have full freedom to configure everything as I, the Dev, like it.

Sadly the scripts used to manipulate the config files of Apache are undocumented (no comments or you stripped these from the distirbution package, who knows?) and they're not really structured in any obvious way. At some point I simply decided it would be much quicker just setting up a webserver an PHP by hand than investing hours into understanding and modifying the PHP scripts, only to replace them after every update.

That and the reaction time to Github issues made me switch to a new "handmade" dev environment. 
(6 months is just unacceptable, even for a hobby project. I think if one doesn't have a few minutes every week to do support, one shouldn't even publish such a project to begin with)

**Comment by mastacheata** [comment]
Just one more technical remark:
If you really want that artificial limitation, do it on the server level (in the Listen directive by binding to 127.0.0.1 / ::1) and not on directory level. The IP in the VHosts is not supposed to be a restriction in the first place, but is to be used if you want to provide different content based on which way the request reaches the webserver. It's obviously possible to do a restriction that way as well, but it's considered "bad practice" (as opposed to a "best practice").
