### ISSUE TITLE
LIBPQ.dll Missing

### ISSUE THREAD

**Issue by Kobra299** [easyphp/easyphp-devserver#80]
I try to run the APACHE version : 2.4.23
compiler : VC14
architecture : x86 (64-bit)
supported languages : PHP, Python, Ruby, Perl

and every time I do it says something about not finding the LIBPQ.dll not sure why its saying this will try to get screen shot of it next time I run it

**Comment by unostar** [comment]
This is about PostgreSQL. I am so tired of this as well. Developers should either add PostgreSQL to the dist or comment out these lines in php.ini:

`
extension=php_pdo_pgsql.dll
extension=php_pgsql.dll
`

**Comment by easyphp** [comment]
Noted! We will fix this.

**Comment by burgutex** [comment]
Same error in use with Dev Server 17. What is the solution? Please share it. I checked extension=php_pdo_pgsql.dll extension=php_pgsql.dll lines in php.ini. Commented out.

**Comment by unostar** [comment]
Just updated to latest version. In my php714vc14x64x170507032953 php.ini lines are still active. Should be:

;extension=php_pdo_pgsql.dll
;extension=php_pgsql.dll

**Comment by easyphp** [comment]
Fixed now. Sorry about that.

**Comment by Kobra299** [comment]
it was skiped on  php715vc14x64x170615193050
