### ISSUE TITLE
Missing MySQL Plugin

### ISSUE THREAD

**Issue by BewilderedAgain** [easyphp/easyphp-devserver#81]
On a fresh install of DevServer 16.1.1 on Win10 and after adding a user and database, when I try to log on to MySQL I get the error message ERROR 1524 (HY000): Plugin '*1066DCAA4FD897C973A6BE30F6507BFAA07F8A61' is not loaded

There is generaly odd behaviour in phpMyadim too, but I dont want to obfuscate things.

**Comment by MirekBalik** [comment]
I've had this problem too. There seemed a database -> mysql to be damaged (by select -> error: wrong structure... ).
I worked around	this and now it works for me:-) .
In fact, it is a mistake that is already in the installation package that arosed during upgrading mySQL to 5.7.11 version.

Here  is my approach to patch:   
1.  Uninstall EasyPHP-DevServer (simply delete <Install-Directory> (By me: EasyPHP-Devserver-16.1 in directory: C:\Program files(x86)).
2.  Run new install of EasyPHP-DevServer-16.1.
3.  Open my.ini file in <Install-Directory>\eds-binaries\dbserver\mysql5711x86x161013204522\ and 
	in section [mysqld] write this lines:
		skip-grant-tables
		show_compatibility_56 = 1 

4.  Open file: <Install-Directory>\eds-modules\phpmyadmin4551x161013204522\config.inc.php and comment this line:
    // $cfg['Servers'][$i]['hide_db']= '(mysql|information_schema|performance_schema|test|phpmyadmin)';

5.  Run EasyPHP-DevServer and open PhpMyAdmin
6.  Look in database mysql and follow instructions by Aasim and Rolando here:
	http://dba.stackexchange.com/questions/54608/innodb-error-table-mysql-innodb-table-stats-not-found-after-upgrade-to-mys
	
6.  Open Commandline Window (cmd) as administator.
7.  Change a directory (cd) to: <Install-Directory>\EasyPHP-Devserver-16.1\eds-binaries\dbserver\mysql5711x86x161013204522\bin
8.  Run this: mysql_upgrade.exe   --protocol=tcp -P 3306 
9.  If upgrade process completed successfuly restart DevServer.
10. Now follow the instructions in documentation of PhpMyAdmin to include  database phpadmin  and create pma user with rights to it. You  must also adjust the file  config.inc.php. Preferably by the AdjustingScript in PhpMyAdmin .
11. Reset DevServer and run in command window this:
	mysql_upgrade.exe   --protocol=tcp -P 3306 --force
12. In my.ini comment line: skip-grant-tables, reset DevServer and enjoy.

My configuration: Win7 (64bit) SP1 CZ version; MSIE 11; DevServer 16.1 ( mySQL 5.7.11 (x86); PhpMyAdmin 4.5.5.1).

**Comment by BewilderedAgain** [comment]
Thank you for the detailed information. 

BA
