### ISSUE TITLE
After installing php 5.6.25  - different modul API in compiling

### ISSUE THREAD

**Issue by petros55** [easyphp/easyphp-devserver#84]
PHP Startup: gd: Unable to initialize module 
Module compiled with modul API=20131226 PHP compiled with module API=20121212
Theese options need do match

easyPHP 16.1.1

**Comment by REJack** [comment]
It's sounds like that you use PHP 5.5 extensions in PHP 5.6,

check your php.ini there is a entry `extension_dir` it need to be filled correctly to your php folder of the specific version, this entry get filled automaticly on the installation.

My entry: 
```extension_dir = "C:\Program Files (x86)\EasyPHP-Devserver-16.1\eds-binaries\php\php5625vc11x86x160915124759\ext"```

**Comment by REJack** [comment]
If you have a PHP Installation in your system environment variable `PATH` assigned, remove it or change it to the same PHP version that you use in EasyPHP.

**Comment by petros55** [comment]
First of all I reinstalled easyPHP. With PHP 5.6.19 and PHP 7.0.4. Everything worked fine. 
Installation of PHP 7.1.0 was the second step. Everything worked fine. 
Third step was critical. :-D Installation of PHP 5.6.25 was the issue! And the same error appeared. 

So, I don't think that the problem is as you described. :-(

**Comment by REJack** [comment]
can you use the PHP from your CMD?

**Comment by petros55** [comment]
What are you expecting?

**Comment by REJack** [comment]
If you have a PHP Installation in your system environment variable PATH assigned (php is executable from anywhere in cmd), then the other/new PHP installation use the PHP modules from the PATH's assigned PHP.

An example based on my error:
If your system environment variable PATH is assigend to PHP 5.5 and you use PHP 5.6 in easyPHP then i get error message like you

```
PHP Warning:  PHP Startup: curl: Unable to initialize module\nModule compiled with module API=20131226\nPHP    compiled with module API=20121212\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: gd: Unable to initialize module\nModule compiled with module API=20131226\nPHP    compiled with module API=20121212\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: mbstring: Unable to initialize module\nModule compiled with module API=20131226\nPHP    compiled with module API=20121212\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: mysql: Unable to initialize module\nModule compiled with module API=20131226\nPHP    compiled with module API=20121212\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: mysqli: Unable to initialize module\nModule compiled with module API=20131226\nPHP    compiled with module API=20121212\nThese options need to match\n in Unknown on line 0
PHP Warning:  PHP Startup: openssl: Unable to initialize module\nModule compiled with module API=20131226\nPHP    compiled with module API=20121212\nThese options need to match\n in Unknown on line 0
```

I had the same problem, i assign PHP for linting in my texteditor, now i need only change the PHP version to the active version in easyPHP with a cmd script to avoid this error.
