### ISSUE TITLE
Virtual hosts without port

### ISSUE THREAD

**Issue by sancdan** [easyphp/easyphp-devserver#86]
Hi,

I've installed VHosts Manager 1.7. When I create a new virtual host, it appears in the list, but when I click it I receive an error, the page couldn't load. I realized that the end of the url there isn't the port number (:8888). When I type it the end of the url, it works. Is it a bug or I do something wrong?
I used erlier the VHosts Manager 1.1 and it put automatically the port to the end of the url. 

Thanks.

**Comment by REJack** [comment]
You can change the port over the httpserver settings in application over the dashboard.
