### ISSUE TITLE
Connecting NetBeans 8.1 IDE for use with MYSQL Server

### ISSUE THREAD

**Issue by Flamtapper1** [easyphp/easyphp-devserver#87]
I'm trying to configure NetBeans 8.1 to run SQL Server but when I input the settings into the connection Window it displays the following message
 'Unable to connect to the MySQL Server'

org.netbeans.api.db.explorer.DatabaseException: org.netbeans.api.db.explorer.DatabaseException: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server..

The server may not be running or your MySQL connection properties may not be set correctly.  Do you want to edit your MySQL connection properties?

Can anyone help as I need to get cracking with my College stuff on MySQL asap???

**Comment by easyphp** [comment]
If you're not talking about a bug, please ask your question on http://stackoverflow.com/ or there http://www.easyphp.org/discussions_devserver.php
