### ISSUE TITLE
EasyPHP-Devserver-16.1.1-setup.exe  junkware detected ! ?

### ISSUE THREAD

**Issue by LLOz** [easyphp/easyphp-devserver#88]
Hi all,

I downloaded  EasyPHP-Devserver-16.1.1-setup.exe  
at :
http://www.easyphp.org/save-easyphp-devserver-latest.php?d=direct

My G DATA TOTAL PROTECTION  detected a junkware (PUP) in this setup file?

What to think about it ?

Thanks,

**Comment by mikerockett** [comment]
More than likely a false-positive.

**Comment by easyphp** [comment]
Yes, it's a false positive. No worries.
