### ISSUE TITLE
Quickier switching PHP version

### ISSUE THREAD

**Issue by Komanc** [easyphp/easyphp-devserver#89]
It would be nice to have ability to switch PHP version without manually stopping server (Stop server,  select version, start server - too many clicks and "too" much time waiting between those steps) . Something where I select version, confirm and server restart will be done automatically.

**Comment by REJack** [comment]
that is a nice idea 👍

**Comment by bgatellier** [comment]
I cannot agree more !

**Comment by easyphp** [comment]
Hi! You'll find this feature in the next version.
