### ISSUE TITLE
The program can't start because api-ms-win-crt-runtime-l1-1-0.dll 

### ISSUE THREAD

**Issue by davyyg** [easyphp/easyphp-devserver#91]
The program can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer.  Try reinstalling the program to fix this problem.

How to fix those error messages?

I don't have to subscribe to "Updates & Tools" right in easyphp ?

**Comment by mikerockett** [comment]
If you haven't solved this as yet: run Windows Updates, download the Visual C++ redistribution in the correct flavour from [here](https://www.microsoft.com/en-us/download/details.aspx?id=53840). If that's already installed, the installer will prompt you to uninstall. Then run it again to re-install.
