### ISSUE TITLE
Not getting PHP to run

### ISSUE THREAD

**Issue by Tolmeister** [easyphp/easyphp-devserver#92]
Hi, i am having trouble with my local installation; It won't run PHP.

All the rest works just fine, the HTML comes trough nicely , the CSS renders but it ignores stuff like:

  <?php include("menu.php"); ?>
  <?php include("slide1.php"); ?>

As for the dashboard that also works like a charm, i just can't get my PHP content to run locally.
I am currently on build 16.1.1 , i also installed it on my windows 8 laptop too see if my pc's win 7 install had gone the way of the  Dodo but this is not the case it would seem.

A friend of mine helped me configure it months ago, so maybe he tweaked something that got undone. Dunno what happened in between because it worked fine up until now.

I thought it could have been a video game reinstalling or updating visual studio redistribution, so i re-installed that, no luck either!

I hope you guys can help me out, many thanks in advance!

**Comment by mikerockett** [comment]
@Tolmeister - have you managed to sort this out? Does anything change if you switch the PHP version on the dashboard?

**Comment by Hybeki** [comment]
Javascript ou PHP colega ...
