### ISSUE TITLE
MySQL: Cannot change "datadir" setting in my.ini

### ISSUE THREAD

**Issue by dmitrijs** [easyphp/easyphp-devserver#94]
On MySQL start, "datadir" value is reset to default (t.i. "C:/Programs/EasyPHP-Devserver-16.1/eds-binaries/dbserver/mysql5711x86x170114101359/data/")

Is it possible to move data to a custom location?

**Comment by dmitrijs** [comment]
Commenting out replacements in `eds-binaries\dbserver\mysql5711x86x170114101359\eds-app-actions.php` solved the issue for now.

Why is editing of configuration file allowed, if it's content is replaced?

**Comment by Shine753** [comment]
"Why is editing of configuration file allowed, if it's content is replaced?"
Will this be corrected ?
