### ISSUE TITLE
Issue with DB Server with Devserver 16.1

### ISSUE THREAD

**Issue by chrisfooxx** [easyphp/easyphp-devserver#99]
Hello,

I don't know where i need to go in order to find help on my issue. Hope it's here.
I installed easyphp dev server 16.1 on a computer with windows Server 2012.
An Extranet website has been installed, worked fine, was reachable from the web.
But for a few days, Apache crashes again and again without any modification of the content or the computer configs.
When i close DB Server task from the task manager (impossible to stop it from the dashboard; close button not working), Apache doesn't crash anymore. But forcefully no access to the website (WordPress base), error establishing connexion to the database.

I couldn't find any answer on the web to find out what is going on and i'm not very familiar (at all) with Php Mysql Apache and co...
Could you please help me to solve this ?

Thank you in advance
Regards
Chris

**Comment by chrisfooxx** [comment]
Hello, 
I tried to use the contact form on easyphp website, i tried here as well but got no reply anywhere. I can see some other issues with 20 days without replies.
Is there still someone supporting this tool ?
Thank you in advance for any tips or even a simple hello to see there is somebody in the house ;)

**Comment by joluga** [comment]
It is like dead. No answer trough here or Stackoverflow or direct mail. But in the official web site, at the bottom there is an announcement for the 17 version. Maybe this one is been abandoned a lot of time ago. :(

**Comment by chrisfooxx** [comment]
Yes i think EasyPhp is dead or at least is missing support, even for people who rent the key of the extensions warehouse... 
I'm using WampServer now and it's working fine (for now).

**Comment by easyphp** [comment]
Hi. Devserver is for development only. For security and stability reasons, you should not use it as a web server. See EasyPHP Webserver for that.
